# generated by datamodel-codegen:
#   filename:  common.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, PositiveFloat, RootModel, constr


class EidosCommonDefinitions(RootModel[Any]):
    root: Any = Field(..., title='Eidos common definitions')
    """
    Definitions shared across the EIDOS node schemas: dynamic value bindings, time and level controls, timezones, and CSS size and position values.
    """


class Kind(str, Enum):
    """
    Type of runtime source to resolve the value from.
    """

    event = 'event'
    selection = 'selection'
    parameter = 'parameter'


class ValueFrom(EidosModel):
    """
    Reference a value from runtime state such as an event, selection, or parameter. The path is resolved against the referenced source object.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    """
    Type of runtime source to resolve the value from.
    """
    source: constr(min_length=1)
    """
    Identifier of the runtime source. For events this is typically the source path or named event source; for selections and parameters this is the selection or parameter name.
    """
    action: Optional[str] = Field(
        None, examples=['click', 'rightClick', 'doubleClick', 'changeMenuItem']
    )
    """
    Optional event action discriminator when kind is 'event'.
    """
    path: constr(min_length=1)
    """
    Dot-path to the desired value within the resolved source object, for example 'data.siteId', 'data.geometry', or 'object.geometry'.
    """
    required: Optional[bool] = False
    """
    Whether resolution failure should be treated as an error instead of yielding an empty value.
    """


class Resolvable(EidosModel):
    """
    Wrapper object used by schemas that allow literal values to be replaced by a dynamic runtime binding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    valueFrom: ValueFrom
    """
    The runtime binding that supplies the value in place of a literal.
    """


class CurrentTime(RootModel[Union[datetime, constr(pattern=r'^-?P')]]):
    root: Union[datetime, constr(pattern=r'^-?P')] = Field(..., title='Current time')
    """
    Time of current node view. Supports ISO 8601 date-time (e.g., '2025-01-01T00:00:00Z') or ISO 8601 duration relative to now (e.g., 'PT0H' for now, '-P1D' for 1 day ago, 'P7D' for 7 days ahead)
    """


class RangeItem(RootModel[constr(pattern=r'^(-?P|\d{4})')]):
    root: constr(pattern=r'^(-?P|\d{4})')
    """
    ISO 8601 date or date-time (e.g. '2025-01-01T00:00:00Z'), or ISO 8601 duration relative to now (e.g. '-P1D', 'P7D'). A '+' sign is not supported on durations.
    """


class LevelControl(EidosModel):
    """
    Level/depth control for selecting vertical levels in data
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    range: List[float] = Field(..., max_length=2, min_length=2)
    """
    Level range as [min, max], in ascending order and with both ends included. Used with step to generate discrete levels. A descending range generates no levels.
    """
    step: Optional[PositiveFloat] = Field(None, title='Level step')
    """
    Step size between levels when using range. Must be greater than zero. Ignored when levels is provided.
    """
    levels: Optional[List[float]] = None
    """
    Explicit array of discrete level values. If provided and not empty, overrides range/step. The values need not be sorted: the control orders them ascending.
    """
    units: Optional[str] = Field(None, title='Level units')
    """
    Unit label for levels (e.g., 'm', 'hPa', 'ft')
    """
    label: Optional[str] = Field(None, title='Control label')
    """
    Label displayed above the level selector
    """
    default: Optional[float] = Field(None, title='Default level')
    """
    Initial level value. It need not be one of the generated levels: the control snaps to the nearest one. When omitted, the control starts at the lowest level.
    """


class Timezone(
    RootModel[Optional[constr(pattern=r'^[A-Za-z0-9_+:-]+(/[A-Za-z0-9_+-]+)*$')]]
):
    root: Optional[constr(pattern=r'^[A-Za-z0-9_+:-]+(/[A-Za-z0-9_+-]+)*$')] = Field(
        ..., title='Timezone'
    )
    """
    Timezone of the current node view, or null for the default (UTC).
    """


class CssSpec(RootModel[Optional[Union[int, str]]]):
    root: Optional[Union[int, str]] = Field(..., title='CSS spec')
    """
    CSS string or pixels as integer or null
    """


class Position(EidosModel):
    """
    Position of an element relative to the edges of its container. Each offset is a CSS string (e.g. '10px', '5%'), an integer number of pixels, or null when that edge is unset.
    """

    top: Optional[CssSpec] = None
    """
    Offset from the top edge of the container.
    """
    left: Optional[CssSpec] = None
    """
    Offset from the left edge of the container.
    """
    bottom: Optional[CssSpec] = None
    """
    Offset from the bottom edge of the container.
    """
    right: Optional[CssSpec] = None
    """
    Offset from the right edge of the container.
    """


class TimeControl(EidosModel):
    """
    Time control for selecting the current time with a slider and optional play/pause buttons for animation
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    range: List[RangeItem] = Field(..., max_length=2, min_length=2)
    """
    Time range of time control as [start, end]. Each value can be an ISO 8601 date-time or duration (e.g., ['-P1D', 'P7D'] for 1 day ago to 7 days ahead). Durations are relative to now and may be negative.
    """
    step: Optional[Union[PositiveFloat, constr(pattern=r'^-?P')]] = Field(
        None, title='Time step'
    )
    """
    Size of time selector increments. Also used for rounding duration-based times. Can be a number (seconds) or ISO 8601 duration (e.g., 'PT1H' for 1 hour). When omitted, an increment is chosen automatically from the length of the range.
    """
    timezone: Optional[Timezone] = None
    """
    Timezone used to place and label the time axis ticks (default UTC).
    """
    zoomable: Optional[bool] = Field(True, title='Zoomable time axis')
    """
    When true, the time axis can be zoomed with the mouse wheel, double-click, and right-click. Defaults to true.
    """
    lockToNow: Optional[bool] = Field(False, title='Lock to current time')
    """
    When true, the time selector starts locked to the current real-world (wall-clock) time and auto-advances to follow it. Any manual interaction with the slider breaks the lock; it can be re-enabled via the control. Defaults to false.
    """
    global_: Optional[bool] = Field(False, alias='global', title='Global time control')
    """
    When true, this time control drives a shared global time across all eidos instances on the page.
    """
