# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, RootModel, confloat, conint, constr


class DataType(str, Enum):
    """
    Type of data source that determines how the data is accessed and processed. Each type requires different configuration in the dataSpec property.
    """

    oceanql = 'oceanql'
    zarr = 'zarr'
    dataset = 'dataset'
    geojson = 'geojson'
    transform = 'transform'
    pmtiles = 'pmtiles'


class Point(EidosModel):
    """
    Point Model
    """

    coordinates: List[Union[float, int]] = Field(..., title='Coordinates')
    type: Literal['Point'] = Field('Point', title='Type')


class MultiPoint(EidosModel):
    """
    MultiPoint Model
    """

    coordinates: List[List[Union[float, int]]] = Field(
        ..., min_length=1, title='Coordinates'
    )
    type: Literal['MultiPoint'] = Field('MultiPoint', title='Type')


class LineString(EidosModel):
    """
    LineString Model
    """

    coordinates: List[List[Union[float, int]]] = Field(
        ..., min_length=2, title='Coordinates'
    )
    type: Literal['LineString'] = Field('LineString', title='Type')


class Coordinate(RootModel[List[List[Union[float, int]]]]):
    root: List[List[Union[float, int]]]


class MultiLineString(EidosModel):
    """
    MultiLineString Model
    """

    coordinates: List[Coordinate] = Field(..., min_length=1, title='Coordinates')
    type: Literal['MultiLineString'] = Field('MultiLineString', title='Type')


class Polygon(EidosModel):
    """
    Polygon Model
    """

    coordinates: List[Coordinate] = Field(..., min_length=1, title='Coordinates')
    type: Literal['Polygon'] = Field('Polygon', title='Type')


class Coordinate2Item(RootModel[List[List[Union[float, int]]]]):
    root: List[List[Union[float, int]]]


class Coordinate2(RootModel[List[Coordinate2Item]]):
    root: List[Coordinate2Item]


class MultiPolygon(EidosModel):
    """
    MultiPolygon Model
    """

    coordinates: List[Coordinate2] = Field(..., min_length=1, title='Coordinates')
    type: Literal['MultiPolygon'] = Field('MultiPolygon', title='Type')


class Type(str, Enum):
    Feature = 'Feature'


class AggregateOps(str, Enum):
    mean = 'mean'
    min = 'min'
    max = 'max'
    std = 'std'
    sum = 'sum'


class CoordSelector(EidosModel):
    coord: str = Field(..., title='Coordinate name')
    values: List[Union[str, int, float]] = Field(
        ..., title='List of coordinate values to select by'
    )


class GeoFilterType(str, Enum):
    """
    Type of the geofilter. Can be one of:
    - 'feature': Select with a geojson feature
    - 'bbox': Select with a bounding box
    - 'radius': Select within radius of point
    """

    feature = 'feature'
    radius = 'radius'
    bbox = 'bbox'


class ResampleType(str, Enum):
    mean = 'mean'
    nearest = 'nearest'


class TimeFilterType(str, Enum):
    """
    Type of the timefilter. Can be one of:
    - 'range': Select within a time range
    """

    range = 'range'
    series = 'series'


class Coordkeys(RootModel[Dict[constr(pattern=r'^[xyztg]$'), str]]):
    root: Dict[constr(pattern=r'^[xyztg]$'), str]
    """
    Coordinate keys mapping variables to dimensions (x: longitude, y: latitude, z: depth/altitude, g: geometry, t: time)
    """


class Zarr(EidosModel):
    """
    A Zarr group read directly over HTTP. Coordinate variables are identified by coordkeys.
    """

    group: constr(min_length=1)
    """
    Zarr group URL. For a multiscale (pyramid) store this may point either at the store root — where the renderer detects the levels and can open any of them — or directly at one level's child group (e.g. '.../store.zarr/2') to pin that level manually.
    """
    headers: Optional[Dict[constr(pattern=r'^.*$'), str]] = None
    """
    Headers for zarr dataset
    """
    coordkeys: Coordkeys
    """
    Mapping of the group's variables to coordinate dimensions (x: longitude, y: latitude, z: depth/altitude, g: geometry, t: time).
    """
    ttl: Optional[confloat(ge=0.0)] = None
    """
    Zarr cache duration in seconds. When null or omitted, cached data never expires; 0 disables caching entirely; a positive value invalidates the cache after that many seconds.
    """
    forwardAuth: Optional[bool] = False
    """
    Forward the renderer authentication headers (Authorization bearer token) to the zarr service
    """


class Pmtiles(EidosModel):
    """
    A PMTiles v3 archive of MVT vector tiles, read directly over HTTP range requests from static hosting (e.g. an R2/S3 object) — there is no tile server in this path. Consumed by the feature worldlayer, which loads tiles on demand for the current view. Mercator archives cannot contain data beyond +/-85.051129 degrees latitude (excluded when the archive is cooked); globe, first-person and VR views render whichever scheme the archive declares on a best-effort basis.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    url: constr(min_length=1)
    """
    URL of the .pmtiles archive. The host must support HTTP byte-range requests (Range / 206 responses).
    """
    headers: Optional[Dict[constr(pattern=r'^.*$'), str]] = None
    """
    Headers sent with every range request to the archive
    """
    forwardAuth: Optional[bool] = False
    """
    Forward the renderer authentication headers (Authorization bearer token) to the archive host
    """


class Dtype(str, Enum):
    """
    Data type of the variable's values. Advisory only: the renderer infers the type from the data and does not read this property.
    """

    int32 = 'int32'
    int64 = 'int64'
    float32 = 'float32'
    float64 = 'float64'
    string = 'string'


class DataVariable(EidosModel):
    """
    A single variable of an inline dataset: its values, the dimensions they are laid out along, and optional attributes.
    """

    attributes: Optional[
        Dict[constr(pattern=r'^.*$'), Optional[Union[str, float, Dict[str, Any], List]]]
    ] = None
    """
    Attributes of the data variable. Null values are allowed: the datamesh client copies a zarr v2 array's mandatory fill_value into `_fill_value`, which is null when no fill value is defined.
    """
    data: Union[List[Optional[Union[float, str, List, bool, Dict[str, Any], Any]]], Any]
    """
    Data of the variable
    """
    dimensions: List[str]
    """
    Names of the dimensions the variable's data is laid out along, outermost first. Each name must be a key of the dataset's dimensions object.
    """
    dtype: Optional[Dtype] = None
    """
    Data type of the variable's values. Advisory only: the renderer infers the type from the data and does not read this property.
    """


class Dataset(EidosModel):
    """
    Inline dataset
    """

    model_config = ConfigDict(
        extra='allow',
    )
    name: Optional[str] = None
    """
    Optional human-readable name of the dataset.
    """
    attributes: Optional[
        Dict[constr(pattern=r'^[A-Za-z0-9_]*$'), Union[str, float, Dict[str, Any]]]
    ] = None
    """
    Attributes of the dataset
    """
    variables: Dict[constr(pattern=r'^[A-Za-z0-9_]*$'), DataVariable]
    """
    Data variables
    """
    dimensions: Dict[constr(pattern=r'^.*$'), conint(ge=0)]
    """
    Dimensions of the dataset, mapping each dimension name to its length.
    """
    coordkeys: Coordkeys
    """
    Mapping of the dataset's variables to coordinate dimensions (x: longitude, y: latitude, z: depth/altitude, g: geometry, t: time).
    """


class OutputType(str, Enum):
    """
    Schema the transform's return value must conform to. `dataset` validates against the inline Dataset schema; `geojson` validates against a GeoJSON FeatureCollection. Validation runs on every query and a failure rejects the query.
    """

    dataset = 'dataset'
    geojson = 'geojson'


class TransformInputTimefilter(EidosModel):
    """
    Datamesh TimeFilter for a transform input, with one extension: `times` entries additionally accept signed ISO 8601 durations (e.g. '-PT24H'), resolved against the queried time T (the consumer timefilter's times[0]) at query time — the same idiom as timeControl.range. A null entry is an open-ended bound. When the consumer query has no timefilter (e.g. the transform's init seed query), a duration-anchored window cannot resolve and the timefilter is omitted entirely (full extent). Only type 'range' is executable by the client engine at present.
    """

    type: Optional[TimeFilterType] = Field('range', title='Timefilter type')
    """
    Type of the time filter. Only 'range' is executable by the client engine at present; 'series' is a schema-valid Datamesh form that is rejected when the transform initializes.
    """
    times: List[Optional[Union[datetime, constr(pattern=r'^[+-]?P')]]] = Field(
        ..., min_length=1, title='Time range'
    )
    """
    Time bounds of the filter, as [start, end] for type 'range'. Each entry is an ISO 8601 date-time, a signed ISO 8601 duration resolved against the queried time (e.g. '-PT24H'), or null for an open-ended bound.
    """
    resolution: Optional[str] = Field('native', title='Temporal resolution of data')
    """
    Datamesh temporal resolution of the returned data; 'native' keeps the source resolution. Not executable by the client engine yet: any value other than 'native' or null is rejected when the transform initializes.
    """
    resample: Optional[ResampleType] = Field('mean', title='Resampling operator')
    """
    Datamesh operator used when resampling to the requested resolution. Not executable by the client engine yet: any non-null value is rejected when the transform initializes, so omit it or set it to null.
    """


class Aggregate(EidosModel):
    operations: Optional[List[AggregateOps]] = Field(
        ['mean'], title='Aggregate operations to perform'
    )
    spatial: Optional[bool] = Field(True, title='Aggregate over spatial filter')
    temporal: Optional[bool] = Field(True, title='Aggregate over temporal filter')


class TimeFilter(EidosModel):
    type: Optional[TimeFilterType] = Field('range', title='Timefilter type')
    times: List[Optional[Union[datetime, timedelta]]] = Field(
        ..., title='Time range or series'
    )
    resolution: Optional[str] = Field('native', title='Temporal resolution of data')
    resample: Optional[ResampleType] = Field('mean', title='Resampling operator')


class EidosData(EidosModel):
    """
    Data source specification for EIDOS visualizations. Defines how to access and process data from various sources including Oceanum Datamesh, Zarr arrays, inline datasets, GeoJSON features, and data transformations. Each data source has a unique ID that can be referenced by visualization components.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^[A-Za-z0-9_-]+$') = Field(
        ...,
        examples=[
            'sig-wave-height-trki',
            'ship-positions',
            'weather-data',
            'hs-1',
            'spec-1',
        ],
    )
    """
    Unique identifier for this data source within the specification. Must be alphanumeric with hyphens and underscores only. This ID is used to reference the data source from visualization layers and components.
    """
    dataType: DataType = Field(..., examples=['dataset', 'geojson', 'transform'])
    """
    Type of data source that determines how the data is accessed and processed. Each type requires different configuration in the dataSpec property.
    """
    dataSpec: Union[
        Dataset, Transform, FeatureCollection, Feature, Oceanql, Zarr, Pmtiles
    ]
    """
    Configuration of the data source. The accepted form depends on dataType: 'dataset' takes an inline Dataset, 'transform' a Transform, 'geojson' a GeoJSON Feature or FeatureCollection, 'oceanql' a Datamesh OceanQL query, 'zarr' a Zarr group and 'pmtiles' a PMTiles archive.
    """
    name: Optional[str] = None
    """
    Optional human-readable name for this data source. Not required; accepted so that specs which annotate a data source with a name do not hard-fail under additionalProperties:false ($defs.dataset and $defs.transform already accept a name).
    """
    description: Optional[str] = None
    """
    Optional human-readable description of this data source. Not required; accepted so that specs which annotate a data source with a description do not hard-fail under additionalProperties:false.
    """


class FeatureCollection(EidosModel):
    type: Literal['FeatureCollection'] = 'FeatureCollection'
    features: List[Feature]


class GeometryCollection(EidosModel):
    """
    GeometryCollection Model
    """

    type: Literal['GeometryCollection'] = Field('GeometryCollection', title='Type')
    geometries: List[Geometry] = Field(..., title='Geometries')


class Geometry(
    RootModel[
        Union[
            Point,
            MultiPoint,
            LineString,
            MultiLineString,
            Polygon,
            MultiPolygon,
            GeometryCollection,
        ]
    ]
):
    root: Union[
        Point,
        MultiPoint,
        LineString,
        MultiLineString,
        Polygon,
        MultiPolygon,
        GeometryCollection,
    ] = Field(..., title='Geometry')
    """
    Geometry Model
    """


class Feature(EidosModel):
    """
    Feature Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type = Field(..., title='Type')
    geometry: Geometry
    properties: Optional[Dict[str, Any]] = Field(None, title='Properties')
    id: Optional[str] = Field(None, title='Id')
    bbox: Optional[List[Union[float, int]]] = Field(None, title='Bbox')


class Oceanql(EidosModel):
    datasource: str = Field(..., title='The id of the datasource')
    parameters: Optional[Dict[str, Any]] = Field({}, title='Datasource parameters')
    description: Optional[str] = Field(None, title='Optional description of this query')
    variables: Optional[List[str]] = Field(None, title='List of selected variables')
    timefilter: Optional[TimeFilter] = Field(None, title='Time filter')
    geofilter: Optional[GeoFilter] = Field(None, title='Spatial filter or interpolator')
    coordfilter: Optional[List[CoordSelector]] = Field(
        None, title='List of additional coordinate filters'
    )
    crs: Optional[Union[int, str]] = Field(
        None, title='Spatial reference for filter and output'
    )
    aggregate: Optional[Aggregate] = Field(None, title='Aggregate operations')
    limit: Optional[int] = Field(None, title='Limit size of response')
    id: Optional[str] = Field(None, title='Unique ID of this query')


class GeoFilter(EidosModel):
    type: Optional[GeoFilterType] = Field('bbox', title='GeoFilter type')
    geom: Union[List[float], Feature] = Field(..., title='bbox OR geojson Feature')
    resolution: Optional[float] = Field(0.0, title='Maximum spatial resolution of data')
    alltouched: Optional[bool] = Field(None, title='Include all touched grid pixels')


class Transform(EidosModel):
    """
    Derives a new data source by running user-supplied JavaScript against one or more existing data sources. The code executes in a sandboxed Web Worker and is re-evaluated on every query. Each input is resolved with the propagated consumer query merged per-field against that input's own query overrides (see the inputs items), so a transform can e.g. widen an input to a time window while the app-level time/region selection is still re-applied to the transform's output. The result is validated against the schema for the declared outputType.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None
    """
    Human readable name of this transform instance
    """
    modules: Optional[Dict[constr(pattern=r'^[A-Za-z_$][A-Za-z0-9_$]*$'), str]] = None
    """
    ES modules to make available inside the transform function. Each entry maps an identifier name to a module URL; the compiled transform module imports it as `import * as <identifier> from '<url>'`, so the module's namespace object is available inside `code` under that identifier (EID-126; previously bound as an extra function argument — alias references in code are unaffected). Example: { "d3": "https://cdn.jsdelivr.net/npm/d3@7/+esm" } exposes the d3 namespace as `d3` inside `code`.
    """
    inputs: List[TransformInput]
    """
    Per-input Datamesh queries resolving the data sources whose results are passed to the transform (EID-125). Each entry's `datasource` must match the `id` of another entry in `data`; an unmodified input is {"datasource": "<data-id>"}. At query time each input is resolved (in declaration order) with the consumer's propagated query merged per-field against the entry's overrides (field present → override, absent → inherit, explicit null → drop), and the results are exposed inside `code` as the `$inputs` object, keyed both positionally ($inputs[0]) and by datasource id ($inputs['my-source']).
    """
    outputType: Optional[OutputType] = 'dataset'
    """
    Schema the transform's return value must conform to. `dataset` validates against the inline Dataset schema; `geojson` validates against a GeoJSON FeatureCollection. Validation runs on every query and a failure rejects the query.
    """
    code: str = Field(..., title='Transform code')
    """
    Body of the transform function (no `function` wrapper, no parameter list — just the body, with a `return` statement). The body is compiled into an ES module as `export default async function ($inputs, $query, $outputType) { <code> }` (EID-126) and may use await. Arguments: `$inputs` — object of resolved input data, each entry available both positionally (`$inputs[0]`) and by source ID (`$inputs['my-source']`, the `datasource` ids from the `inputs` array); `$query` — the original query object propagated from the caller (typically containing time/region selections), unaffected by per-input query overrides; `$outputType` — the configured outputType string. Each `modules` entry is imported at the top of the compiled module and its namespace is available under its alias identifier. The return value must match the `outputType` schema.
    """


class TransformInput(EidosModel):
    """
    Datamesh Query resolving one transform input (EID-125). `datasource` is the id of another data source in this specification. The remaining Datamesh query fields merge per-field with the query propagated from the transform's consumer: field present → override, absent → inherit, explicit null → drop that field from the query. Duplicate `datasource` entries (same source, different queries) are legal, but they collide on the named `$inputs` key — the last entry wins; use positional access ($inputs[i]) to disambiguate. Query forms the client engine cannot execute yet (timefilter type 'series', timefilter resolution/resample, non-bbox geofilters, geofilter interp/resolution/alltouched, and non-null coordfilter/aggregate/crs) are schema-valid Datamesh forms but are rejected with a visible error when the transform initializes.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    datasource: constr(pattern=r'^[A-Za-z0-9_-]+$')
    """
    Id of another data source in this specification (an entry in `data`) that resolves this input.
    """
    variables: Optional[List[str]] = Field(None, title='List of selected variables')
    """
    Variables to request from this input. Overrides the consumer query's `variables` (which name the transform's OUTPUT variables); null requests all of the input's variables. The query result contains only the listed variables, so include every variable the transform code reads — including coordinate variables (e.g. lon/lat/time).
    """
    timefilter: Optional[TransformInputTimefilter] = Field(None, title='Time filter')
    """
    Time filter for this input. Overrides the consumer query's timefilter; null drops it (full time extent).
    """
    geofilter: Optional[GeoFilter] = Field(None, title='Spatial filter')
    """
    Datamesh GeoFilter for this input. Overrides the consumer query's geofilter (typically the viewport bbox); null drops it (full spatial extent).
    """
    coordfilter: Optional[List[CoordSelector]] = Field(
        None, title='List of additional coordinate filters'
    )
    """
    Datamesh coordinate selectors for this input, each selecting values along a named coordinate. Not executable by the client engine yet: a non-null value is rejected when the transform initializes.
    """
    aggregate: Optional[Aggregate] = Field(None, title='Aggregate operations')
    """
    Datamesh aggregate operations for this input. Not executable by the client engine yet: a non-null value is rejected when the transform initializes.
    """
    crs: Optional[Union[int, str]] = Field(
        None, title='Spatial reference for filter and output'
    )
    """
    Datamesh spatial reference for the filter geometry and the output, as an EPSG code (integer) or a CRS string. Not executable by the client engine yet: a non-null value is rejected when the transform initializes.
    """


EidosData.model_rebuild()
FeatureCollection.model_rebuild()
GeometryCollection.model_rebuild()
Oceanql.model_rebuild()
Transform.model_rebuild()
