# generated by datamodel-codegen:
#   filename:  oceanql.json
#   timestamp: 2024-08-17T05:50:19+00:00
#
# Hand-maintained: autogen/gen_models.sh does not regenerate this file.
# It needs oceanum (the data extra), so eidosxr.spec does not import it eagerly —
# OceanQL is resolved lazily by eidosxr.spec.__getattr__ (see autogen/gen_init.py).

from __future__ import annotations

from ._basemodel import EidosModel
from .._optional import import_optional

Query = import_optional("oceanum.datamesh").Query


class OceanQL(EidosModel, Query):
    """
    Top-level specification of an OceanQL query
    """
