# generated by datamodel-codegen:
#   filename:  theme.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import conint, constr


class Preset(str, Enum):
    """
    Color scheme for the view
    """

    default = 'default'
    dark = 'dark'


class ColorStyle(EidosModel):
    """
    Color palette configuration
    """

    primary: Optional[str] = '#0d2d3f'
    """
    Primary color of the view
    """
    secondary: Optional[str] = '#a9dce0'
    """
    Secondary color of the view
    """
    accent: Optional[str] = '#b84528'
    """
    Accent color of the view
    """
    background: Optional[str] = '#ffffff'
    """
    Background color of the view
    """


class TextStyle(EidosModel):
    """
    Typography configuration
    """

    color: Optional[str] = '#212529'
    """
    Text color of the view
    """
    fontFamily: Optional[str] = (
        'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"'
    )
    """
    Font family of the view
    """
    fontSize: Optional[Union[str, conint(ge=0)]] = '14px'
    """
    Font size of the text, as a CSS size string (e.g. '14px', '1rem') or an integer number of pixels
    """
    fontWeight: Optional[
        constr(
            pattern=r'^(normal|bold|bolder|lighter|inherit|initial|unset|1000|[1-9][0-9]{0,2})$'
        )
    ] = '400'
    """
    Font weight of the text, as a CSS font-weight string: 'normal', 'bold', 'bolder', 'lighter' or a numeric weight from 1 to 1000 (e.g. '600')
    """
    lineHeight: Optional[Union[str, conint(ge=0)]] = '1.5'
    """
    Line height of the text, as a CSS line-height string (e.g. '1.5', '20px'). An integer is interpreted as pixels, so use a string for a unitless multiplier.
    """
    align: Optional[str] = 'left'
    """
    Text alignment of the view
    """
    titleSize: Optional[Union[str, conint(ge=0)]] = '2.0rem'
    """
    Size of the title, as a CSS size string or an integer number of pixels
    """
    subtitleSize: Optional[Union[str, conint(ge=0)]] = '1.5rem'
    """
    Size of the subtitle, as a CSS size string or an integer number of pixels
    """
    headingSize: Optional[Union[str, conint(ge=0)]] = '1.15rem'
    """
    Size of the heading, as a CSS size string or an integer number of pixels
    """


class ControlStyle(EidosModel):
    """
    Control element styling
    """

    opacity: Optional[str] = '0.5'
    """
    Opacity of control elements, as a string holding a number from 0 to 1 (e.g. '0.5')
    """
    borderColor: Optional[str] = '#ffffff77'
    """
    Border color of control elements
    """
    backgroundColor: Optional[str] = '#ffffff55'
    """
    Background color of control elements
    """
    textColor: Optional[str] = '#212529'
    """
    Text color of control elements
    """
    borderWidth: Optional[Union[str, conint(ge=0)]] = '1px'
    """
    Border width of control elements, as a CSS size string or an integer number of pixels
    """
    borderStyle: Optional[
        constr(
            pattern=r'^(none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|inherit|initial|unset)( (none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset)){0,3}$'
        )
    ] = 'solid'
    """
    Border style of control elements, as a CSS border-style value (one to four of none, hidden, dotted, dashed, solid, double, groove, ridge, inset, outset)
    """
    borderRadius: Optional[Union[str, conint(ge=0)]] = '0.375rem'
    """
    Border radius of control elements, as a CSS size string or an integer number of pixels
    """
    backdropFilter: Optional[str] = 'blur(18px)'
    """
    Backdrop filter effect for controls
    """
    boxShadow: Optional[str] = '0 0.5rem 1rem rgba(0, 0, 0, 0.15)'
    """
    Box shadow effect for controls
    """
    boxShadowInset: Optional[str] = 'inset 0 0px 8px #575757'
    """
    Inset box shadow effect for controls
    """


class PanelStyle(EidosModel):
    """
    Panel element styling
    """

    opacity: Optional[str] = '1.0'
    """
    Opacity of panel elements, as a string holding a number from 0 to 1 (e.g. '1.0')
    """
    borderColor: Optional[str] = '#ffffff77'
    """
    Border color of panel elements
    """
    backgroundColor: Optional[str] = '#ffffff55'
    """
    Background color of panel elements
    """
    textColor: Optional[str] = '#212529'
    """
    Text color of panel elements
    """
    borderWidth: Optional[Union[str, conint(ge=0)]] = '1px'
    """
    Border width of panel elements, as a CSS size string or an integer number of pixels
    """
    borderStyle: Optional[
        constr(
            pattern=r'^(none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|inherit|initial|unset)( (none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset)){0,3}$'
        )
    ] = 'solid'
    """
    Border style of panel elements, as a CSS border-style value (one to four of none, hidden, dotted, dashed, solid, double, groove, ridge, inset, outset)
    """
    borderRadius: Optional[Union[str, conint(ge=0)]] = '0.375rem'
    """
    Border radius of panel elements, as a CSS size string or an integer number of pixels
    """
    backdropFilter: Optional[str] = 'blur(18px)'
    """
    Backdrop filter effect for panels
    """
    boxShadow: Optional[str] = '0 0.5rem 1rem rgba(0, 0, 0, 0.15)'
    """
    Box shadow effect for panels
    """
    boxShadowInset: Optional[str] = 'inset 0 0px 8px #575757'
    """
    Inset box shadow effect for panels
    """


class GridStyle(EidosModel):
    """
    Grid element styling
    """

    borderWidth: Optional[Union[str, conint(ge=0)]] = '0px'
    """
    Border width of grid elements, as a CSS size string or an integer number of pixels
    """
    borderRadius: Optional[Union[str, conint(ge=0)]] = '0.375rem'
    """
    Border radius of grid elements, as a CSS size string or an integer number of pixels
    """
    borderStyle: Optional[
        constr(
            pattern=r'^(none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|inherit|initial|unset)( (none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset)){0,3}$'
        )
    ] = 'solid'
    """
    Border style of grid elements, as a CSS border-style value (one to four of none, hidden, dotted, dashed, solid, double, groove, ridge, inset, outset)
    """
    borderColor: Optional[str] = '#0d2d3f'
    """
    Border color of grid elements
    """
    padding: Optional[Union[str, conint(ge=0)]] = '0'
    """
    Padding of grid elements, as a CSS size string or an integer number of pixels
    """
    margin: Optional[Union[str, int]] = '0'
    """
    Margin of grid elements, as a CSS size string or an integer number of pixels. May be negative.
    """
    backgroundColor: Optional[str] = 'transparent'
    """
    Background color of grid elements
    """


class EidosStyle(EidosModel):
    """
    Style properties organized by category
    """

    color: Optional[ColorStyle] = None
    """
    Color palette (primary, secondary, accent and background colors).
    """
    text: Optional[TextStyle] = None
    """
    Typography (text color, font family, sizes, weight, line height and alignment).
    """
    control: Optional[ControlStyle] = None
    """
    Styling of control elements.
    """
    panel: Optional[PanelStyle] = None
    """
    Styling of floating panels.
    """
    grid: Optional[GridStyle] = None
    """
    Styling of grid cells.
    """


class EidosTheme(EidosModel):
    """
    Visual theme of an EIDOS specification: a color-scheme preset plus optional style overrides grouped by category (color, text, control, panel, grid).
    """

    preset: Optional[Preset] = 'default'
    """
    Color scheme for the view
    """
    style: Optional[EidosStyle] = None
    """
    Style overrides applied on top of the preset.
    """
