# generated by datamodel-codegen:
#   filename:  node/document.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from typing import Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, constr

from .. import theme


class DocumentStyle(EidosModel):
    """
    Document style overrides
    """

    text: Optional[theme.TextStyle] = None
    """
    Typography overrides for the document text (color, font family, sizes, weight, line height and alignment).
    """


class Document(EidosModel):
    """
    Content node that renders templated markdown text. Use it for narrative content alongside maps and plots, for example a report section or help text in a grid cell or panel.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    """
    Unique identifier for this document node within the specification. Used for referencing this node in events, interactions, and programmatic access.
    """
    title: Optional[str] = None
    """
    Title of the document
    """
    nodeType: Literal['document'] = 'document'
    """
    Node type identifier. Must be 'document' for markdown content nodes.
    """
    content: str
    """
    Document content as templated markdown
    """
    style: Optional[DocumentStyle] = None
    """
    Style overrides applied to this document only.
    """
