# generated by datamodel-codegen:
#   filename:  node/menu.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, constr

from . import derived, document, grid, plot, world


class Position(str, Enum):
    """
    Location of menu relative to content. Reserved: not currently applied by the renderer, which always places the menu above the content.
    """

    top = 'top'
    left = 'left'
    bottom = 'bottom'
    right = 'right'


class MenuLayoutItem(EidosModel):
    """
    Configuration of nodes in menu layout
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    label: Union[str, List[str]]
    """
    Label of the menu item: a string for a top-level item, or [parent, item] to place the item in a submenu. Entries sharing the same parent label are grouped under one submenu.
    """
    icon: Optional[
        Union[
            constr(pattern=r'^$|^[A-Za-z][A-Za-z0-9+.-]*:'),
            List[Optional[constr(pattern=r'^$|^[A-Za-z][A-Za-z0-9+.-]*:')]],
        ]
    ] = None
    """
    Icon of the menu item: an absolute image URL, or a built-in Phosphor icon given as 'icon://<name>' with optional 'weight' and 'color' query parameters. For a hierarchical label, give [parent icon, item icon].
    """


class Menu(EidosModel):
    """
    Layout node that shows one child node at a time, selected through a navigation menu. Each child node is paired with the menuLayout entry at the same index, which supplies its menu label and icon.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    """
    Unique identifier for this menu node within the specification. Used for referencing this node in events, interactions, and programmatic access.
    """
    nodeType: Literal['menu'] = 'menu'
    """
    Node type identifier. Must be 'menu' for menu layout containers.
    """
    activeItem: Optional[constr(min_length=1)] = None
    """
    ID of the child node shown initially. Defaults to the first child. Can be changed at runtime to switch the displayed node.
    """
    position: Optional[Position] = 'top'
    """
    Location of menu relative to content. Reserved: not currently applied by the renderer, which always places the menu above the content.
    """
    open: Optional[bool] = True
    """
    Whether menu is open. Reserved: not currently used by the renderer.
    """
    children: List[
        Union[world.Nested, plot.Plot, document.Document, grid.Grid, derived.Derived]
    ]
    """
    Child nodes selectable through the menu; one is displayed at a time. Must have the same number of entries as menuLayout, which supplies the menu item for the child at the same index.
    """
    openOnMouseOver: Optional[bool] = False
    """
    Expand a submenu when the pointer moves over it and collapse it when the pointer leaves, instead of on click. Only affects hierarchical menus (menuLayout entries with a [parent, item] label).
    """
    menuLayout: List[MenuLayoutItem]
    """
    Menu items, one per child node and paired with children by index. Must have the same number of entries as children: if the lengths differ, no menu items are shown.
    """


# model_rebuild() called in panel.py after EidosPanel is defined to break circular import
