# generated by datamodel-codegen:
#   filename:  node/plot.json
#   timestamp: 2026-08-03T04:03:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict

from .. import common, vegaspec


class PlotType(str, Enum):
    """
    Unused — the renderer always treats plotSpec as vega-lite (see vega-container.tsx). Kept for backward compatibility with existing specs that set it (EID-102); not removed because plot.json is additionalProperties:false and dropping the property would reject those specs.
    """

    vega = 'vega'
    vega_lite = 'vega-lite'


class Plot(EidosModel):
    """
    Specification for plot view environmental digital twin display and interaction
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique id of the node
    """
    title: Optional[str] = None
    """
    Title of the plot
    """
    nodeType: Literal['plot'] = 'plot'
    plotType: Optional[PlotType] = None
    """
    Unused — the renderer always treats plotSpec as vega-lite (see vega-container.tsx). Kept for backward compatibility with existing specs that set it (EID-102); not removed because plot.json is additionalProperties:false and dropping the property would reject those specs.
    """
    plotSpec: vegaspec.TopLevelSpec
    actions: Optional[Dict[str, Any]] = None
    """
    Actions to enable for the plot. Unused — vega-container.tsx hardcodes actions:false to the vega-embed call (the export toggle is commented out); the object itself is left open (no additionalProperties:false) for forward compatibility with specs that already set it (EID-102).
    """
    fitToContainer: Optional[bool] = True
    """
    Resize the plot to fit its container. When true (the default) single/layer views fill the container and vconcat panes are distributed across it; when false the plot keeps its authored width/height and the container scrolls.
    """
    timezone: Optional[common.Timezone] = None
    currentTime: Optional[common.CurrentTime] = None
    timeControl: Optional[common.TimeControl] = None
