# generated by datamodel-codegen:
#   filename:  node/plot.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, constr

from .. import common, vegaspec


class PlotType(str, Enum):
    """
    Unused — the renderer always treats plotSpec as vega-lite (see vega-container.tsx). Kept for backward compatibility with existing specs that set it (EID-102); not removed because plot.json is additionalProperties:false and dropping the property would reject those specs.
    """

    vega = 'vega'
    vega_lite = 'vega-lite'


class Plot(EidosModel):
    """
    Content node that renders a chart from a Vega-Lite specification. Plots can bind to the data sources defined in the root 'data' array and can carry their own current time, timezone and time control.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    """
    Unique identifier for this plot node within the specification. Used for referencing this node in events, interactions, and programmatic access.
    """
    title: Optional[str] = None
    """
    Title of the plot
    """
    nodeType: Literal['plot'] = 'plot'
    """
    Node type identifier. Must be 'plot' for chart nodes.
    """
    plotType: Optional[PlotType] = None
    """
    Unused — the renderer always treats plotSpec as vega-lite (see vega-container.tsx). Kept for backward compatibility with existing specs that set it (EID-102); not removed because plot.json is additionalProperties:false and dropping the property would reject those specs.
    """
    plotSpec: vegaspec.TopLevelSpec
    actions: Optional[Dict[str, Any]] = None
    """
    Actions to enable for the plot. Unused — vega-container.tsx hardcodes actions:false to the vega-embed call (the export toggle is commented out); the object itself is left open (no additionalProperties:false) for forward compatibility with specs that already set it (EID-102).
    """
    fitToContainer: Optional[bool] = True
    """
    Resize the plot to fit its container. When true (the default) single/layer views fill the container and vconcat panes are distributed across it; when false the plot keeps its authored width/height and the container scrolls.
    """
    timezone: Optional[common.Timezone] = None
    """
    Timezone used for this plot (default UTC).
    """
    currentTime: Optional[common.CurrentTime] = None
    """
    Time of the current plot view, as an ISO 8601 date-time or an ISO 8601 duration relative to now.
    """
    timeControl: Optional[common.TimeControl] = None
    """
    Time control for this plot. Omit for a plot without a time slider.
    """
