# generated by datamodel-codegen:
#   filename:  node/world.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, RootModel, confloat, constr

from .. import common
from .worldlayer import feature, gridded
from .worldlayer import label as label_1
from .worldlayer import pointcloud, scenegraph, seasurface, track, wmts


class ViewType(Enum):
    """
    Type of world view for a nested world node. Only 'map' and 'globe' are allowed; 'vr', 'fp' and 'ar' require the world node to be the specification root.
    """

    map = 'map'
    globe = 'globe'


class BaseLayerPreset(str, Enum):
    """
    Base layer preset. 'oceanum' is the Oceanum cartography; 'outdoors', 'light', 'dark', 'satellite', 'satellite-streets' and 'mapbox' are the standard Mapbox styles. 'terrain' is DEPRECATED — use satellite-streets with the world terrain option instead; legacy specs are normalized to that pairing with a deprecation warning.
    """

    oceanum = 'oceanum'
    outdoors = 'outdoors'
    light = 'light'
    dark = 'dark'
    satellite = 'satellite'
    satellite_streets = 'satellite-streets'
    mapbox = 'mapbox'
    terrain = 'terrain'


class BaseLayerConfig(EidosModel):
    """
    Custom base map defined by a Mapbox style URL and an optional access token.
    """

    url: Optional[constr(min_length=1)] = Field(
        None, examples=['mapbox://styles/mapbox/satellite-streets-v12']
    )
    """
    URL to the mapbox style for the base layer
    """
    accessToken: Optional[str] = None
    """
    Authentication token for the base layer
    """


class ViewType1(str, Enum):
    """
    Type of world view. 'map' is a standard mercator map, 'globe' renders the world as a globe, 'fp' is a monoscopic first-person view anchored at the longitude/latitude point, 'vr' is the stereoscopic (side-by-side) variant of the first-person view, and 'ar' is a first-person view with no basemap whose camera is driven by an external vessel pose feed (poseSource) over a live camera video background (videoSource). 'vr', 'fp' and 'ar' are only valid when the world node is the root node of the specification.
    """

    map = 'map'
    globe = 'globe'
    vr = 'vr'
    fp = 'fp'
    ar = 'ar'


class Fog(EidosModel):
    """
    Atmosphere for the immersive view types ('vr'/'fp'), mirroring mapbox setFog(): distant geometry fades to 'color' and the sky blends from 'highColor' down to 'color' at the horizon. Defaults derive the fog color from the basemap style's background.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    color: Optional[str] = None
    """
    Lower-atmosphere / fog color (CSS color string).
    """
    highColor: Optional[str] = None
    """
    Upper-atmosphere sky color (CSS color string).
    """
    horizonBlend: Optional[confloat(ge=0.0, le=1.0)] = 0.02
    """
    Thickness of the horizon blend band as a fraction of the viewport height.
    """


class Type(str, Enum):
    """
    Pose feed protocol. 'signalk' subscribes to navigation.position, navigation.headingTrue and navigation.attitude on a Signal K server's WebSocket stream (Signal K reports angles in radians; they are converted internally).
    """

    signalk = 'signalk'


class Boresight(EidosModel):
    """
    Camera mounting misalignment relative to the vessel's AHRS frame, in degrees, added to the reported heading and pitch. Set during installation so the overlay registers with the real horizon and landmarks.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    heading: Optional[float] = 0
    """
    Degrees added to the vessel heading to get the camera bearing (positive clockwise).
    """
    pitch: Optional[float] = 0
    """
    Degrees added to the vessel pitch to get the camera pitch (positive up).
    """


class VerticalReference(str, Enum):
    """
    Vertical datum for the camera height. 'seaSurface' (marine default): the camera sits at the fixed cameraOffset up component above the water and the reported GNSS altitude is ignored. 'gnss': the reported altitude is added to the up component — note GNSS altitude is WGS84-ellipsoidal, so anchored content must use the same reference.
    """

    seaSurface = 'seaSurface'
    gnss = 'gnss'


class PoseSource(EidosModel):
    """
    External camera pose feed that drives the 'ar' view camera. The reported vessel position and attitude replace user camera interaction: the view continuously re-anchors at the vessel's longitude/latitude with the camera bearing/pitch from the vessel heading and attitude. Only used by the 'ar' view type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    """
    Pose feed protocol. 'signalk' subscribes to navigation.position, navigation.headingTrue and navigation.attitude on a Signal K server's WebSocket stream (Signal K reports angles in radians; they are converted internally).
    """
    url: str = Field(
        ...,
        examples=[
            'http://localhost:3000',
            'wss://vessel.example.com/signalk/v1/stream',
        ],
    )
    """
    Signal K server root (http(s)://host[:port]) or full stream URL (ws(s)://host/signalk/v1/stream).
    """
    token: Optional[str] = None
    """
    Optional Signal K access token, appended to the stream URL as a query parameter.
    """
    boresight: Optional[Boresight] = None
    """
    Camera mounting misalignment relative to the vessel's AHRS frame, in degrees, added to the reported heading and pitch. Set during installation so the overlay registers with the real horizon and landmarks.
    """
    cameraOffset: Optional[List[float]] = Field(
        [0, 0, 2], examples=[[2, 0, 3]], max_length=3, min_length=3
    )
    """
    Camera position in the vessel body frame as [forward, starboard, up] meters from the GNSS position; rotated by the vessel heading into world coordinates each update. The up component sets the camera height above the vertical reference.
    """
    verticalReference: Optional[VerticalReference] = 'seaSurface'
    """
    Vertical datum for the camera height. 'seaSurface' (marine default): the camera sits at the fixed cameraOffset up component above the water and the reported GNSS altitude is ignored. 'gnss': the reported altitude is added to the up component — note GNSS altitude is WGS84-ellipsoidal, so anchored content must use the same reference.
    """
    staleTimeout: Optional[confloat(ge=0.5)] = 5
    """
    Seconds without a pose update before the overlay is flagged as stale.
    """


class Type3(str, Enum):
    """
    'camera' uses the device camera via getUserMedia (rear-facing by default); 'url' plays a web-playable video stream URL (e.g. an MJPEG or progressive MP4 endpoint from a vessel IP camera).
    """

    camera = 'camera'
    url = 'url'


class VideoSource(EidosModel):
    """
    Live camera video composited behind the transparent deck canvas for the 'ar' view type. Omit for overlay-only AR (layers render against the page background). Only used by the 'ar' view type.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type3
    """
    'camera' uses the device camera via getUserMedia (rear-facing by default); 'url' plays a web-playable video stream URL (e.g. an MJPEG or progressive MP4 endpoint from a vessel IP camera).
    """
    deviceId: Optional[str] = None
    """
    Specific camera device id for type 'camera' (from enumerateDevices). Defaults to the environment-facing camera.
    """
    url: Optional[str] = None
    """
    Stream URL for type 'url'.
    """


class View(EidosModel):
    """
    Camera configuration defining the initial viewport of the map including position, zoom level, and orientation. This sets how users first see the map when it loads.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    viewType: Optional[ViewType1] = 'map'
    """
    Type of world view. 'map' is a standard mercator map, 'globe' renders the world as a globe, 'fp' is a monoscopic first-person view anchored at the longitude/latitude point, 'vr' is the stereoscopic (side-by-side) variant of the first-person view, and 'ar' is a first-person view with no basemap whose camera is driven by an external vessel pose feed (poseSource) over a live camera video background (videoSource). 'vr', 'fp' and 'ar' are only valid when the world node is the root node of the specification.
    """
    longitude: confloat(ge=-180.0, le=180.0) = Field(..., examples=[174.3, -122.4, 2.3])
    """
    Longitude coordinate of the map center in decimal degrees (-180 to 180). Positive values are East, negative values are West.
    """
    latitude: confloat(ge=-90.0, le=90.0) = Field(..., examples=[-38.5, 37.7, 48.9])
    """
    Latitude coordinate of the map center in decimal degrees (-90 to 90). Positive values are North, negative values are South.
    """
    pitch: Optional[confloat(ge=-90.0, le=90.0)] = 0
    """
    Pitch angle of the view in degrees. For the 'map' and 'globe' view types 0 looks straight down and the camera is limited to the range 0 to maxPitch. The immersive view types ('vr', 'fp', 'ar') also allow a negative pitch, down to -90.
    """
    bearing: Optional[float] = 0
    """
    Bearing of the view in degrees clockwise from north. Values outside -180 to 180 are accepted and normalized into that range.
    """
    maxZoom: Optional[confloat(ge=0.0)] = 20
    """
    Maximum zoom level the camera can be zoomed in to. If omitted, the renderer uses 18.
    """
    zoom: Optional[confloat(ge=0.0)] = Field(0, examples=[2, 8, 12, 16])
    """
    Initial zoom level of the map. Higher values show more detail. Typically ranges from 0 (world view) to 20+ (street level). May be fractional. If omitted, the renderer uses 5. Not used by the immersive view types ('vr', 'fp', 'ar'), which use position instead.
    """
    maxPitch: Optional[confloat(ge=0.0, le=90.0)] = 60
    """
    Maximum pitch angle in degrees. If omitted, the renderer uses 85 for the 'map' and 'globe' view types and 90 for the immersive view types.
    """
    position: Optional[List[float]] = Field(
        [0, 0, 2], examples=[[0, 0, 2], [0, 0, 100]], max_length=3, min_length=3
    )
    """
    Camera offset from the longitude/latitude anchor point as [east, north, up] in meters. Only used by the 'vr' and 'fp' view types; the third component sets the camera height above the surface.
    """
    fov: Optional[confloat(ge=10.0, le=140.0)] = 75
    """
    Vertical field of view of the camera in degrees. Only used by the 'vr' and 'fp' view types.
    """
    ipd: Optional[confloat(ge=0.03, le=0.12)] = 0.064
    """
    Interpupillary distance in meters — the stereo separation between the left and right eye cameras. Only used by the 'vr' view type.
    """
    fog: Optional[Fog] = None
    """
    Atmosphere for the immersive view types ('vr'/'fp'), mirroring mapbox setFog(): distant geometry fades to 'color' and the sky blends from 'highColor' down to 'color' at the horizon. Defaults derive the fog color from the basemap style's background.
    """
    zoomOut: Optional[confloat(ge=0.0, le=1.0)] = Field(None, examples=[0.85, 1])
    """
    Degree of zoom-out for the 'globe' view type, from actual scale to the full globe: 0 places the camera at true scale (one screen pixel is approximately one meter at the anchor latitude) and 1 zooms all the way out to the whole globe. Takes precedence over 'zoom' when set, and camera interaction keeps it in sync. Only used by the 'globe' view type.
    """
    poseSource: Optional[PoseSource] = None
    """
    External camera pose feed that drives the 'ar' view camera. The reported vessel position and attitude replace user camera interaction: the view continuously re-anchors at the vessel's longitude/latitude with the camera bearing/pitch from the vessel heading and attitude. Only used by the 'ar' view type.
    """
    videoSource: Optional[VideoSource] = None
    """
    Live camera video composited behind the transparent deck canvas for the 'ar' view type. Omit for overlay-only AR (layers render against the page background). Only used by the 'ar' view type.
    """


class HoverInfo(EidosModel):
    """
    Properties for tooltip shown on hover
    """

    template: str = Field(..., examples=['{{name}}: {{round hs 1}} m'])
    """
    Tooltip as Handlebars template, rendered as HTML. The render context is the properties of the picked object (or the picked object itself when it has no properties), so the available fields depend on the layer type. The helpers round(value, decimals), multiply(value, factor), add(value, amount) and degrees_to_cardinal(value) are available; each returns '-' for a non-numeric value. An empty result shows no tooltip.
    """


class Units(str, Enum):
    """
    Units for the point radius. 'pixels' draws a constant screen-size marker; the geographic options size the marker in the smaller unit of the pair (m for m/km and m/nm, ft for ft/mi) so it scales with the map. Note: m/km and m/nm produce the same point size — the pair notation mirrors the radius-control units enum.
    """

    pixels = 'pixels'
    m_km = 'm/km'
    m_nm = 'm/nm'
    ft_mi = 'ft/mi'


class Config(EidosModel):
    """
    Configuration of the points control.
    """

    radius: Optional[confloat(ge=0.0)] = Field(20, title='Point radius')
    """
    Radius of points drawn on the map, expressed in the selected units. Defaults to 20 (pixels).
    """
    units: Optional[Units] = Field('pixels', title='Radius units')
    """
    Units for the point radius. 'pixels' draws a constant screen-size marker; the geographic options size the marker in the smaller unit of the pair (m for m/km and m/nm, ft for ft/mi) so it scales with the map. Note: m/km and m/nm produce the same point size — the pair notation mirrors the radius-control units enum.
    """


class Control1(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['points'] = 'points'
    """
    Points control: draws up to 100 points on the map, combined into a single MultiPoint. Right-click a point to move it.
    """
    config: Optional[Config] = None
    """
    Configuration of the points control.
    """


class Control2(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['polygon'] = 'polygon'
    """
    Polygon control: draws a single polygon on the map. Drawing a new polygon replaces the previous one. Right-click the polygon to edit its vertices.
    """
    config: Optional[Dict[str, Any]] = None
    """
    Configuration of the polygon control. No options are currently defined.
    """


class Control3(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['bbox'] = 'bbox'
    """
    Bounding box control: draws a single rectangle on the map. Drawing a new rectangle replaces the previous one.
    """
    config: Optional[Dict[str, Any]] = None
    """
    Configuration of the bounding box control. No options are currently defined.
    """


class Units1(str, Enum):
    """
    Units for the radius readout. Each option is a small/large pair; the readout switches between them by magnitude.
    """

    m_km = 'm/km'
    m_nm = 'm/nm'
    ft_mi = 'ft/mi'


class Config1(EidosModel):
    """
    Configuration of the radius control.
    """

    units: Optional[Units1] = Field('m/km', title='Radius units')
    """
    Units for the radius readout. Each option is a small/large pair; the readout switches between them by magnitude.
    """


class Control4(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['radius'] = 'radius'
    """
    Radius control: draws a single circle on the map from its center outwards. Drawing a new circle replaces the previous one.
    """
    config: Optional[Config1] = None
    """
    Configuration of the radius control.
    """


class Control5(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['drop'] = 'drop'
    """
    Drop control: while active, the map cursor is replaced by the control's icon so the user can drop it at a location. It draws nothing on the map itself; the interaction is reported through a 'drop' event.
    """
    config: Optional[Dict[str, Any]] = None
    """
    Configuration of the drop control. No options are currently defined.
    """


class Control6(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['measure'] = 'measure'
    """
    Measure control: measures the distance along a path clicked on the map.
    """
    config: Optional[Dict[str, Any]] = None
    """
    Configuration of the measure control. No options are currently defined.
    """


class Config2(EidosModel):
    """
    Configuration of the panel control.
    """

    panelId: str = Field(..., examples=['info-panel', 'data-panel'])
    """
    ID of the panel to open when this control is clicked. Must match a panel ID in root.panels.
    """


class Control7(EidosModel):
    """
    A map control button. config is specific to each nodeType.
    """

    nodeType: Literal['panelopen'] = 'panelopen'
    """
    Panel control: a button that opens or closes the panel named by config.panelId. Unlike the other controls it is not a map tool and does not stay active.
    """
    config: Config2
    """
    Configuration of the panel control.
    """


class Control(
    RootModel[
        Union[Control1, Control2, Control3, Control4, Control5, Control6, Control7]
    ]
):
    root: Union[
        Control1, Control2, Control3, Control4, Control5, Control6, Control7
    ] = Field(..., title='Control')
    """
    A map control button. config is specific to each nodeType.
    """


class Orientation(str, Enum):
    """
    Orientation of the control group
    """

    horizontal = 'horizontal'
    vertical = 'vertical'


class ControlGroup(EidosModel):
    """
    A group of map control buttons, laid out in a row or column at a position within the map container.
    """

    id: constr(min_length=1)
    """
    Control group id. Forms part of the event source path of its controls: '<world path>/children/#<group id>/children/#<control id>'.
    """
    nodeType: Literal['controlgroup'] = 'controlgroup'
    """
    Node type identifier. Must be set to 'controlgroup': the renderer only recognizes a world child as a control group when this is present.
    """
    orientation: Optional[Orientation] = 'vertical'
    """
    Orientation of the control group
    """
    position: Optional[common.Position] = Field(
        default_factory=lambda: common.Position.model_validate(
            {'top': None, 'left': None, 'bottom': None, 'right': None}
        )
    )
    """
    Position of the control group within the map container. Specify top/left/right/bottom as pixel numbers; CSS strings are not supported here. Defaults to top: 100, left: 10 if unset.
    """
    children: List[Control]
    """
    Control list. Controls are shown in order; a group with no controls renders nothing.
    """
    visible: Optional[bool] = True
    """
    Visibility of control group. Set this to true explicitly: the renderer currently treats an omitted value as false, so a group without it is not shown.
    """


class LayerSelector(EidosModel):
    """
    Layer selector: the panel listing the world node's layers with their legends, where users toggle layer visibility.
    """

    open: Optional[bool] = True
    """
    Whether the layer selector starts expanded. Set this explicitly: the renderer currently treats an omitted value as false, so the selector starts collapsed.
    """
    title: Optional[str] = None
    """
    Optional title displayed at the top of the open layer selector (legend panel).
    """


class Mode(str, Enum):
    """
    Time selection mode. 'nearest' selects the time step closest to the current time, within tolerance. 'range' selects every time step from the current time onwards. 'exact' is not currently implemented and applies no time filtering.
    """

    nearest = 'nearest'
    exact = 'exact'
    range = 'range'


class Aggregate(str, Enum):
    """
    Aggregation method for time range. Reserved: not currently used by the renderer, which returns the selected time steps unaggregated.
    """

    last = 'last'
    first = 'first'
    sum = 'sum'
    mean = 'mean'
    max = 'max'
    min = 'min'


class TimeSelect(EidosModel):
    """
    Time selection criteria for layer
    """

    mode: Mode
    """
    Time selection mode. 'nearest' selects the time step closest to the current time, within tolerance. 'range' selects every time step from the current time onwards. 'exact' is not currently implemented and applies no time filtering.
    """
    tolerance: Optional[constr(pattern=r'^-?P')] = Field(
        None, examples=['PT60S', 'PT1H', 'P1D']
    )
    """
    Time tolerance for nearest time select, as an ISO 8601 duration (e.g. 'PT1H'): the nearest time step is only used when it lies within this distance of the current time. Defaults to 'PT60S'.
    """
    aggregate: Optional[Aggregate] = Field('last', title='Time aggregation')
    """
    Aggregation method for time range. Reserved: not currently used by the renderer, which returns the selected time steps unaggregated.
    """
    groupby: Optional[str] = None
    """
    Data variable to group by. In 'nearest' mode, the nearest time step is selected separately for each distinct value of this variable, giving one record per group (e.g. the latest position of each vessel). Applied by feature, label, pointcloud and scenegraph layers.
    """


class Mode1(str, Enum):
    """
    Level selection mode. 'nearest' selects the level closest to the current level, within tolerance. 'range' is not usable at present: layers supply a single level rather than a range, so it selects no levels and blanks the layer. 'exact' is not currently implemented and applies no level filtering.
    """

    nearest = 'nearest'
    exact = 'exact'
    range = 'range'


class LevelSelect(EidosModel):
    """
    Level selection criteria for layer
    """

    mode: Optional[Mode1] = 'nearest'
    """
    Level selection mode. 'nearest' selects the level closest to the current level, within tolerance. 'range' is not usable at present: layers supply a single level rather than a range, so it selects no levels and blanks the layer. 'exact' is not currently implemented and applies no level filtering.
    """
    tolerance: Optional[confloat(ge=0.0)] = None
    """
    Level tolerance for nearest level select, in the units of the level coordinate: the nearest level is only used when it lies within this distance of the current level. When omitted, the nearest level is always used.
    """
    level: Optional[float] = None
    """
    Default level value for this layer, used when the world node supplies no current level.
    """


class ViewState(View):
    """
    Camera configuration of a nested world node, restricted to the non-immersive view types.
    """

    viewType: Optional[ViewType] = None
    """
    Type of world view for a nested world node. Only 'map' and 'globe' are allowed; 'vr', 'fp' and 'ar' require the world node to be the specification root.
    """


class BaseLayer(RootModel[Optional[Union[BaseLayerPreset, BaseLayerConfig]]]):
    root: Optional[Union[BaseLayerPreset, BaseLayerConfig]] = Field(
        ..., title='Base layer'
    )
    """
    Base map providing the background cartography: a named preset, a custom Mapbox style, or null for no base map.
    """


class World(EidosModel):
    """
    Interactive 2D/3D map node for displaying geospatial and oceanic data. World nodes can contain multiple data layers (gridded data, features, tracks, etc.) and provide map controls, time navigation, and spatial interaction capabilities. Ideal for visualizing spatial data, environmental conditions, and geographic features.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1) = Field(..., examples=['map-1', 'world-view', 'main-map'])
    """
    Unique identifier for this world node within the specification. Used for referencing this node in events, interactions, and programmatic access.
    """
    title: Optional[str] = None
    """
    Human-readable title for this world node.
    """
    nodeType: Literal['world'] = 'world'
    """
    Node type identifier. Must be 'world' for map/globe visualizations.
    """
    children: List[Union[WorldLayer, ControlGroup, panel_1.EidosPanel]]
    """
    Array of world layers and controls to display on this map. Each layer represents a different data visualization (e.g., gridded data, vector features, tracks, 3D objects). Layers are rendered in order with later layers appearing on top.
    """
    baseLayer: Optional[BaseLayer] = None
    """
    Base map layer providing the background cartography. Can be a preset like 'oceanum' or 'satellite-streets', or a custom tile layer configuration.
    """
    terrain: Optional[bool] = False
    """
    Render the basemap over 3D terrain. Independent of baseLayer — works with any basemap source. Worldlayers opt into terrain-relative z with their terrainFollow option.
    """
    qualityScale: Optional[confloat(le=4.0, gt=0.0)] = 1
    """
    LOD quality dial for multiscale datasources (GeoZarr pyramids, PMTiles). 1 (the default) requests roughly one data cell per screen pixel. Lower is coarser and cheaper, higher is sharper and costlier: 0.5 selects about one pyramid level coarser for ~4x less data, 2 about one level finer for ~4x more — data volume scales with the square of this value. No effect on flat (non-multiscale) datasources, or on a datasource pinned to an explicit group.
    """
    viewState: Optional[View] = None
    """
    Initial camera position and orientation for the map view, including center coordinates, zoom level, pitch, and bearing.
    """
    currentTime: Optional[common.CurrentTime] = None
    """
    Time of current world view. If omitted, defaults to the start of the timeControl range when one is defined, otherwise to now.
    """
    timeControl: Optional[common.TimeControl] = None
    """
    Time control configuration. Set to null to disable the time control, or provide an object to customize its appearance and behavior.
    """
    levelControl: Optional[common.LevelControl] = None
    """
    Level control configuration. Set to null to disable the level control, or provide an object to customize its appearance and behavior.
    """
    currentLevel: Optional[float] = None
    """
    Current level value for the world view
    """
    layerSelector: Optional[LayerSelector] = None
    """
    Layer selector control configuration. Set to null to disable the layer selector, or provide an object to customize its appearance and behavior.
    """


class LayerSpec(
    RootModel[
        Union[
            feature.FeatureLayer,
            gridded.GriddedLayer,
            label_1.LabelLayer,
            scenegraph.ScenegraphLayer,
            pointcloud.PointCloudLayer,
            seasurface.SeaSurfaceLayer,
            track.TrackLayer,
            wmts.WmtsLayerSpec,
        ]
    ]
):
    root: Union[
        feature.FeatureLayer,
        gridded.GriddedLayer,
        label_1.LabelLayer,
        scenegraph.ScenegraphLayer,
        pointcloud.PointCloudLayer,
        seasurface.SeaSurfaceLayer,
        track.TrackLayer,
        wmts.WmtsLayerSpec,
    ]
    """
    Layer specification
    """


class WorldLayer(EidosModel):
    """
    A data layer displayed on a world map. World layers visualize different types of geospatial data including gridded datasets (like temperature, wave height), vector features (points, lines, polygons), tracks (moving objects), and 3D scene elements.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1) = Field(
        ..., examples=['wave-height', 'ship-tracks', 'weather-stations']
    )
    """
    Unique identifier for this layer within the world node. Used for layer management, visibility control, and programmatic access.
    """
    name: Optional[str] = Field(
        None, examples=['Significant Wave Height', 'Ship Positions', 'Weather Stations']
    )
    """
    Display name for this layer shown in the layer selector and legend. Should be descriptive and user-friendly.
    """
    nodeType: Literal['worldlayer'] = 'worldlayer'
    """
    Node type identifier. Must be 'worldlayer' for data layers of a world node.
    """
    dataId: Optional[str] = Field(
        None, examples=['hs-1', 'sig-wave-height-trki', 'ship-positions']
    )
    """
    Reference to a data source defined in the root 'data' array. This connects the layer to its data source for visualization.
    """
    visible: Optional[bool] = True
    """
    Whether this layer is initially visible when the map loads. Users can toggle visibility through the layer selector. Set this explicitly: the renderer currently treats an omitted value as false, so a layer without it starts hidden.
    """
    exclusiveOf: Optional[List[str]] = []
    """
    Layer IDs that cannot be displayed at the same time as this layer. An empty array or omitted property means this layer is compatible with all other layers. The relation is symmetric: declaring it on either of the two layers is enough. When a layer becomes visible, any visible layer it excludes is hidden.
    """
    linked: Optional[str] = None
    """
    ID of another layer in the same world node which controls this layer's visibility. A linked layer is shown and hidden together with the layer it is linked to rather than being toggled on its own.
    """
    hoverInfo: Optional[HoverInfo] = None
    """
    Configuration for tooltips displayed when hovering over layer elements. Uses Handlebars templates for dynamic content.
    """
    label: Optional[str] = None
    """
    Display label for this layer. Reserved: not currently used by the renderer. The layer selector shows the legend title, then the layer name, then the layer id.
    """
    panel: Optional[str] = None
    """
    ID of a panel associated with this layer. Must match a panel ID in root.panels. Reserved: not currently used by the renderer, which does not open a panel when a layer is selected.
    """
    layerSpec: LayerSpec
    """
    Layer-type specific configuration. The layerType property selects the layer implementation (feature, gridded, label, scenegraph, pointcloud, seasurface, track or wmts) and determines which other properties apply.
    """
    minZoom: Optional[confloat(ge=0.0)] = 0
    """
    Minimum zoom level at which layer is visible (inclusive). Use a whole number: visibility is re-evaluated when the zoom crosses a whole-number boundary.
    """
    maxZoom: Optional[confloat(ge=0.0)] = 24
    """
    Maximum zoom level at which layer is visible (inclusive). Use a whole number: visibility is re-evaluated when the zoom crosses a whole-number boundary. 0 is treated as unset and falls back to 24.
    """
    timeSelect: Optional[TimeSelect] = None
    """
    Time selection criteria for layer
    """
    levelSelect: Optional[LevelSelect] = None
    """
    Level selection criteria for layer
    """


class Nested(World):
    """
    World node used anywhere other than the specification root (grid or menu children, panels). Identical to the root world node except that the immersive view types ('vr', 'fp', 'ar') are not allowed.
    """

    viewState: Optional[ViewState] = None
    """
    Camera configuration of a nested world node, restricted to the non-immersive view types.
    """


# model_rebuild() called in panel.py after EidosPanel is defined to break circular import
# model_rebuild() called in panel.py after EidosPanel is defined to break circular import
