# generated by datamodel-codegen:
#   filename:  node/worldlayer/common.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import AnyUrl, ConfigDict, Field, RootModel, confloat


class WorldlayerCommonProperties(EidosModel):
    """
    Common properties for worldlayer nodes
    """


class TerrainFollow(RootModel[bool]):
    root: bool = Field(..., title='Terrain follow')
    """
    Interpret z coordinates as height above the terrain surface. Requires the world node terrain option to be enabled; warns and falls back to ellipsoid z when it is not.
    """


class ScaledColormap(EidosModel):
    """
    Custom colormap defined by a list of colors and the domain values they correspond to. A numeric domain gives a continuous color scale; a domain of strings gives a categorical mapping.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    scale: List[str] = Field(..., min_length=1)
    """
    Colors of the colormap. For a numeric domain the colors are interpolated across the domain. For a categorical domain each color applies to the domain value at the same position, so there must be at least as many colors as domain values.
    """
    domain: List[Union[float, str]] = Field(..., min_length=1)
    """
    Domain of the colormap. Numbers define a continuous scale (the min and max values, or one value per color). Strings define a categorical mapping, where each value takes the color at the same position in scale; include the value '_default' to set the color used for any value not listed.
    """


class Name(str, Enum):
    """
    Name of the preset colormap
    """

    turbo = 'turbo'
    viridis = 'viridis'
    cividis = 'cividis'
    inferno = 'inferno'
    magma = 'magma'
    plasma = 'plasma'
    d3 = 'd3'
    g10 = 'g10'
    t10 = 't10'
    alphabet = 'alphabet'
    dark24 = 'dark24'
    light24 = 'light24'
    twilight = 'twilight'
    icefire = 'icefire'
    edge = 'edge'
    phase = 'phase'
    hsv = 'hsv'
    mrybm = 'mrybm'
    mygbm = 'mygbm'
    turbid = 'turbid'
    thermal = 'thermal'
    haline = 'haline'
    solar = 'solar'
    ice = 'ice'
    gray = 'gray'
    oxy = 'oxy'
    deep = 'deep'
    dense = 'dense'
    algae = 'algae'
    matter = 'matter'
    speed = 'speed'
    amp = 'amp'
    tempo = 'tempo'
    balance = 'balance'
    delta = 'delta'
    curl = 'curl'
    wind = 'wind'
    wave = 'wave'
    purples = 'purples'
    blues = 'blues'
    greens = 'greens'
    oranges = 'oranges'
    reds = 'reds'
    ylorbr = 'ylorbr'
    ylorrd = 'ylorrd'
    orrd = 'orrd'
    purd = 'purd'
    rdpu = 'rdpu'
    bupu = 'bupu'
    pubu = 'pubu'
    pubugn = 'pubugn'
    gnbu = 'gnbu'
    bugn = 'bugn'
    ylgnbu = 'ylgnbu'
    ylgn = 'ylgn'
    greys = 'greys'
    spectral = 'spectral'
    rdylgn = 'rdylgn'
    rdbu = 'rdbu'
    piyg = 'piyg'
    prgn = 'prgn'
    rdylbu = 'rdylbu'
    brbg = 'brbg'
    rdgy = 'rdgy'
    set1 = 'set1'
    pastel1 = 'pastel1'
    dark2 = 'dark2'
    set2 = 'set2'
    pastel2 = 'pastel2'
    set3 = 'set3'


class PresetColormap(EidosModel):
    """
    Predefined colormap
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name
    """
    Name of the preset colormap
    """
    domain: Optional[List[float]] = Field(None, max_length=20, min_length=2)
    """
    Domain of the preset colormap. Two values are taken as [min, max] and expanded into evenly spaced color stops; more than two values are used as the explicit color stops. Required for every preset except 'wind' and 'wave', which carry their own domain; for those, a [min, max] domain clips the preset to that range.
    """


class ColorItem(RootModel[confloat(ge=0.0, le=255.0)]):
    root: confloat(ge=0.0, le=255.0)


class Color(RootModel[Union[List[ColorItem], str]]):
    root: Union[List[ColorItem], str] = Field(..., title='Color')
    """
    Color definition, as an [r, g, b] or [r, g, b, a] array or a CSS color string.
    """


class StyleAccessorString(RootModel[str]):
    root: str = Field(..., title='Style accessor constant string')
    """
    Constant value applied to every object. For a color property (name ending in 'Color') this is any CSS color string; for any other property it is a constant string. It is never read as a data field name: use the function or template form to take the value from the data.
    """


class StyleAccessorNumber(RootModel[float]):
    root: float = Field(..., title='Style accessor constant number')
    """
    Constant number applied to every object
    """


class StyleAccessorArray(RootModel[List[float]]):
    """
    Constant array applied to every object, e.g. a color as [r, g, b, a] with components from 0 to 255, or a pixel offset as [x, y]
    """

    root: List[float] = Field(..., title='Style accessor constant array')
    """
    Constant array applied to every object, e.g. a color as [r, g, b, a] with components from 0 to 255, or a pixel offset as [x, y]
    """


class StyleAccessorTemplate(EidosModel):
    """
    Accessor evaluated for each object from a Handlebars template
    """

    template: str = Field(..., examples=['{{name}}', '{{round hs 1}} m'])
    """
    Handlebars template rendered for each object with the object's properties as the context. For a color property (name ending in 'Color') the rendered text is parsed as a CSS color; otherwise it is used as a string. The helpers round, multiply, add and degrees_to_cardinal are available.
    """


class StyleAccessorFunction(EidosModel):
    """
    Accessor evaluated for each object by a function of the object's properties
    """

    function: str = Field(
        ..., examples=['colormapper', 'h * 2', '{return selected ? 4.0 : 2.0}']
    )
    """
    Either the built-in 'colormapper', which maps the data field named by the single entry of args through the layer colormap, or JavaScript source evaluated for each object. The source may be a plain expression ('h * 2'), a statement body ('return h;') or a braced body ('{ return h; }'), and refers to the names listed in args.
    """
    args: List[str]
    """
    Names of the data fields passed to the function, looked up in each object's properties. For JavaScript source each name is also the parameter name the source refers to. For 'colormapper' give exactly one name: the field to map through the colormap.
    """


class LegendSpec(EidosModel):
    """
    Legend properties. The legend is drawn in the layer selector from the layer colormap: a gradient color bar for a numeric domain, or a list of color swatches for a categorical domain.
    """

    title: Optional[str] = None
    """
    Legend title. Also the name shown for the layer in the layer selector, in place of the layer name.
    """
    labels: Optional[List[Union[str, float]]] = None
    """
    Legend labels, replacing the colormap domain values as the tick or swatch labels
    """
    url: Optional[AnyUrl] = None
    """
    URL to an external legend image. Takes precedence over the colormap: when set, the image is shown instead of a color bar.
    """


class Legend(RootModel[Optional[Union[LegendSpec, bool]]]):
    root: Optional[Union[LegendSpec, bool]] = Field(..., title='Legend definition')
    """
    Legend for the layer. false or null shows no legend. true, or omitting the property, shows the default legend built from the layer colormap. An object customizes the legend's title, labels or image.
    """


class Colormap(RootModel[Union[PresetColormap, ScaledColormap]]):
    root: Union[PresetColormap, ScaledColormap] = Field(..., title='Colormap')
    """
    Mapping from data values to colors: either a named preset colormap or a custom list of colors, each with the domain of values it covers.
    """


class StyleAccessor(
    RootModel[
        Union[
            StyleAccessorString,
            StyleAccessorNumber,
            StyleAccessorFunction,
            StyleAccessorArray,
            StyleAccessorTemplate,
        ]
    ]
):
    root: Union[
        StyleAccessorString,
        StyleAccessorNumber,
        StyleAccessorFunction,
        StyleAccessorArray,
        StyleAccessorTemplate,
    ] = Field(..., title='Style accessor definition')
    """
    Value of a style property whose name begins with 'get': either a constant (string, number or array) applied to every object, or a function or template evaluated for each object against its properties.
    """
