# generated by datamodel-codegen:
#   filename:  node/worldlayer/feature.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat, constr

from . import common as common_1


class LineWidthUnits(str, Enum):
    """
    The units of the line width, one of 'meters', 'common', and 'pixels'. Default: 'meters'.
    """

    meters = 'meters'
    common = 'common'
    pixels = 'pixels'


class PointRadiusUnits(str, Enum):
    """
    Units for point radius when pointType is 'circle', one of 'meters', 'common', and 'pixels'. Default: 'meters'.
    """

    meters = 'meters'
    common = 'common'
    pixels = 'pixels'


class IconSizeUnits(str, Enum):
    """
    Units for icon size when pointType is 'icon', one of 'meters', 'common', and 'pixels'. Default: 'pixels'.
    """

    meters = 'meters'
    common = 'common'
    pixels = 'pixels'


class TextSizeUnits(str, Enum):
    """
    Units for text size when pointType is 'text', one of 'meters', 'common', and 'pixels'. Default: 'pixels'.
    """

    meters = 'meters'
    common = 'common'
    pixels = 'pixels'


class TextWordBreak(str, Enum):
    """
    Word break setting for text when pointType is 'text', one of 'break-word' and 'break-all'. Requires a valid textMaxWidth. Default: 'break-word'.
    """

    break_word = 'break-word'
    break_all = 'break-all'


class FeatureStyle(EidosModel):
    """
    Style properties for Feature Layer features
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = None
    """
    Opacity of the layer, from 0 (fully transparent) to 1 (fully opaque). Default: 1.
    """
    pointType: Optional[
        constr(pattern=r'^(circle|icon|text)(\+(circle|icon|text))*$')
    ] = Field(None, examples=['circle', 'icon', 'circle+text', 'icon+text'])
    """
    How to render Point and MultiPoint features in the data. Supported types are 'circle', 'icon', 'text'. To use more than one type, join the names with '+', for example 'icon+text'. Default: 'circle'.
    """
    filled: Optional[bool] = None
    """
    Whether to draw filled polygons (solid fill) and points (circles). Default: true.
    """
    getFillColor: Optional[common_1.StyleAccessor] = None
    """
    The solid color of the polygon and points (circles) in the format [r, g, b, [a]]. Default: [0, 0, 0, 255].
    """
    stroked: Optional[bool] = None
    """
    Whether to draw an outline around polygons and points (circles). Default: true.
    """
    getLineColor: Optional[common_1.StyleAccessor] = None
    """
    The rgba color of a line in the format [r, g, b, [a]]. Default: [0, 0, 0, 255].
    """
    getLineWidth: Optional[common_1.StyleAccessor] = None
    """
    The width of a line in units specified by lineWidthUnits. Default: 1.
    """
    lineWidthUnits: Optional[LineWidthUnits] = None
    """
    The units of the line width, one of 'meters', 'common', and 'pixels'. Default: 'meters'.
    """
    lineWidthScale: Optional[confloat(ge=0.0)] = None
    """
    A multiplier that is applied to all line widths. Default: 1.
    """
    lineWidthMinPixels: Optional[confloat(ge=0.0)] = None
    """
    The minimum line width in pixels. Default: 0.
    """
    lineWidthMaxPixels: Optional[confloat(ge=0.0)] = None
    """
    The maximum line width in pixels. Default: 9007199254740991.
    """
    lineCapRounded: Optional[bool] = None
    """
    Type of line caps. If true, draw round caps. Otherwise draw square caps. Default: false.
    """
    lineJointRounded: Optional[bool] = None
    """
    Type of line joint. If true, draw round joints. Otherwise draw miter joints. Default: false.
    """
    lineMiterLimit: Optional[confloat(ge=0.0)] = None
    """
    The maximum extent of a joint in ratio to the stroke width. Only applies when lineJointRounded is false. Default: 4.
    """
    lineBillboard: Optional[bool] = None
    """
    If true, extrude the line in screen space (width always faces the camera). Default: false.
    """
    extruded: Optional[bool] = None
    """
    Extrude Polygon and MultiPolygon features along the z-axis if set to true. Default: false.
    """
    wireframe: Optional[bool] = None
    """
    Whether to generate a line wireframe of extruded polygons. Only applies when extruded is true. Default: false.
    """
    getElevation: Optional[common_1.StyleAccessor] = None
    """
    The elevation of a polygon feature (when extruded is true). Default: 1000.
    """
    elevationScale: Optional[float] = None
    """
    Elevation multiplier. The final elevation is calculated by elevationScale * getElevation(d). Default: 1.
    """
    material: Optional[Dict[str, Any]] = None
    """
    An object that contains material props for lighting effect applied on extruded polygons. Default: {}.
    """
    field_full3d: Optional[bool] = Field(None, alias='_full3d')
    """
    Experimental property. When true, polygon tessellation will be performed on the plane with the largest area, instead of the xy plane. Default: false.
    """
    getPointRadius: Optional[common_1.StyleAccessor] = None
    """
    Radius of points when pointType is 'circle'. Default: 1.
    """
    pointRadiusUnits: Optional[PointRadiusUnits] = None
    """
    Units for point radius when pointType is 'circle', one of 'meters', 'common', and 'pixels'. Default: 'meters'.
    """
    pointRadiusScale: Optional[confloat(ge=0.0)] = None
    """
    Scale for point radius when pointType is 'circle'. Default: 1.
    """
    pointRadiusMinPixels: Optional[confloat(ge=0.0)] = None
    """
    Minimum point radius in pixels when pointType is 'circle'. Default: 0.
    """
    pointRadiusMaxPixels: Optional[confloat(ge=0.0)] = None
    """
    Maximum point radius in pixels when pointType is 'circle'. Default: 9007199254740991.
    """
    pointAntialiasing: Optional[bool] = None
    """
    Whether to use antialiasing for points when pointType is 'circle'. Default: true.
    """
    pointBillboard: Optional[bool] = None
    """
    If true, point is billboarded when pointType is 'circle'. Default: false.
    """
    iconAtlas: Optional[str] = None
    """
    URL of the icon atlas image when pointType is 'icon'. Default: null.
    """
    iconMapping: Optional[Dict[str, Any]] = None
    """
    Mapping of icon names to positions in the atlas when pointType is 'icon'. Default: {}.
    """
    getIcon: Optional[common_1.StyleAccessor] = None
    """
    Accessor for icon names when pointType is 'icon'. Default: f => f.properties.icon.
    """
    getIconSize: Optional[common_1.StyleAccessor] = None
    """
    Size of icons when pointType is 'icon'. Default: 1.
    """
    getIconColor: Optional[common_1.StyleAccessor] = None
    """
    Color of icons when pointType is 'icon'. Default: [0, 0, 0, 255].
    """
    getIconAngle: Optional[common_1.StyleAccessor] = None
    """
    Rotation angle of icons when pointType is 'icon'. Default: 0.
    """
    getIconPixelOffset: Optional[common_1.StyleAccessor] = None
    """
    Pixel offset of icons when pointType is 'icon'. Default: [0, 0].
    """
    iconSizeUnits: Optional[IconSizeUnits] = None
    """
    Units for icon size when pointType is 'icon', one of 'meters', 'common', and 'pixels'. Default: 'pixels'.
    """
    iconSizeScale: Optional[confloat(ge=0.0)] = None
    """
    Scale for icon size when pointType is 'icon'. Default: 1.
    """
    iconSizeMinPixels: Optional[confloat(ge=0.0)] = None
    """
    Minimum icon size in pixels when pointType is 'icon'. Default: 0.
    """
    iconSizeMaxPixels: Optional[confloat(ge=0.0)] = None
    """
    Maximum icon size in pixels when pointType is 'icon'. Default: 9007199254740991.
    """
    iconBillboard: Optional[bool] = None
    """
    If true, icons are billboarded when pointType is 'icon'. Default: true.
    """
    iconAlphaCutoff: Optional[confloat(ge=0.0, le=1.0)] = None
    """
    Alpha cutoff for icons when pointType is 'icon', from 0 to 1. Pixels with an alpha below this value are discarded. Default: 0.05.
    """
    getText: Optional[common_1.StyleAccessor] = None
    """
    Accessor for text content when pointType is 'text'. Default: f => f.properties.text.
    """
    getTextColor: Optional[common_1.StyleAccessor] = None
    """
    Color of text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    getTextAngle: Optional[common_1.StyleAccessor] = None
    """
    Rotation angle of text when pointType is 'text'. Default: 0.
    """
    getTextSize: Optional[common_1.StyleAccessor] = None
    """
    Size of text when pointType is 'text'. Default: 32.
    """
    getTextAnchor: Optional[common_1.StyleAccessor] = None
    """
    Anchor position of text when pointType is 'text'. Default: 'middle'.
    """
    getTextAlignmentBaseline: Optional[common_1.StyleAccessor] = None
    """
    Alignment baseline of text when pointType is 'text'. Default: 'center'.
    """
    getTextPixelOffset: Optional[common_1.StyleAccessor] = None
    """
    Pixel offset of text when pointType is 'text'. Default: [0, 0].
    """
    getTextBackgroundColor: Optional[common_1.StyleAccessor] = None
    """
    Background color of text when pointType is 'text'. Default: [255, 255, 255, 255].
    """
    getTextBorderColor: Optional[common_1.StyleAccessor] = None
    """
    Border color of text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    getTextBorderWidth: Optional[common_1.StyleAccessor] = None
    """
    Border width of text when pointType is 'text'. Default: 0.
    """
    textSizeUnits: Optional[TextSizeUnits] = None
    """
    Units for text size when pointType is 'text', one of 'meters', 'common', and 'pixels'. Default: 'pixels'.
    """
    textSizeScale: Optional[confloat(ge=0.0)] = None
    """
    Scale for text size when pointType is 'text'. Default: 1.
    """
    textSizeMinPixels: Optional[confloat(ge=0.0)] = None
    """
    Minimum text size in pixels when pointType is 'text'. Default: 0.
    """
    textSizeMaxPixels: Optional[confloat(ge=0.0)] = None
    """
    Maximum text size in pixels when pointType is 'text'. Default: 9007199254740991.
    """
    textCharacterSet: Optional[str] = None
    """
    Character set for text when pointType is 'text'. Default: 'ASCII chars 32-128'.
    """
    textFontFamily: Optional[str] = None
    """
    Font family for text when pointType is 'text'. Default: 'Monaco, monospace'.
    """
    textFontWeight: Optional[str] = None
    """
    Font weight for text when pointType is 'text'. Default: 'normal'.
    """
    textLineHeight: Optional[confloat(ge=0.0)] = None
    """
    Line height for text when pointType is 'text', as a multiple of the text size. Default: 1.
    """
    textMaxWidth: Optional[float] = None
    """
    Maximum width for text when pointType is 'text', as a multiple of the text size, used to wrap text. Any value of 0 or less disables wrapping. Default: -1.
    """
    textWordBreak: Optional[TextWordBreak] = None
    """
    Word break setting for text when pointType is 'text', one of 'break-word' and 'break-all'. Requires a valid textMaxWidth. Default: 'break-word'.
    """
    textBackground: Optional[bool] = None
    """
    Whether text has a background when pointType is 'text'. Default: false.
    """
    textBackgroundPadding: Optional[List[float]] = Field(
        None, max_length=4, min_length=2
    )
    """
    Padding for text background in pixels when pointType is 'text'. Either [horizontal, vertical] or [left, top, right, bottom]. Default: [0, 0].
    """
    textOutlineColor: Optional[common_1.StyleAccessor] = None
    """
    Outline color for text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    textOutlineWidth: Optional[confloat(ge=0.0)] = None
    """
    Outline width for text when pointType is 'text'. Default: 0.
    """
    textBillboard: Optional[bool] = None
    """
    If true, text is billboarded when pointType is 'text'. Default: true.
    """
    textFontSettings: Optional[Dict[str, Any]] = None
    """
    Additional font settings for text when pointType is 'text'. Default: {}.
    """


class FeatureLayer(EidosModel):
    """
    World layer for displaying vector geographic features such as points, lines, and polygons. Ideal for showing discrete objects like weather stations, ship positions, port locations, administrative boundaries, or custom geographic shapes. Features can be styled with colors, symbols, and labels.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common_1.TerrainFollow] = False
    """
    Interpret feature z coordinates as height above the terrain surface. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['feature'] = 'feature'
    """
    Layer type identifier. Must be 'feature' for vector geographic data visualizations.
    """
    colormap: Optional[common_1.Colormap] = None
    """
    Optional color mapping for data-driven feature styling. When provided, feature colors are determined by data values rather than fixed style properties.
    """
    legend: Optional[common_1.Legend] = None
    """
    Configuration for the legend shown for this layer in the layer selector.
    """
    style: Optional[FeatureStyle] = None
    """
    Visual styling properties for features including colors, sizes, stroke properties, and opacity. These styles are applied to all features unless overridden by colormap-based styling.
    """
