# generated by datamodel-codegen:
#   filename:  node/worldlayer/gridded.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, RootModel, confloat, conint

from . import common


class GriddedProps(EidosModel):
    """
    Properties shared by every gridded sublayer (pcolor, particles, partmesh and contour).
    """

    altitude: Optional[float] = None
    """
    Uniform altitude offset for all gridded elements in meters. May be negative. Defaults to 0.
    """
    opacity: Optional[confloat(ge=0.0, le=1.0)] = 1.0
    """
    Opacity of the gridded elements, from 0 (fully transparent) to 1 (fully opaque)
    """
    color: Optional[common.Color] = None
    """
    Uniform color for particles, partmesh glyphs and contour lines, used instead of the layer colormap. The alpha component is ignored; use opacity instead. Defaults to black when the colormap is not applied. Not used by pcolor.
    """


class Pcolor(RootModel[GriddedProps]):
    root: GriddedProps
    """
    Pseudocolor sublayer properties. Only altitude and opacity apply.
    """


class Particles(GriddedProps):
    """
    Animated particle trails advected by the vector field.
    """

    size: Optional[confloat(ge=0.0)] = None
    """
    Size of each particle point in pixels. If omitted, the renderer uses 3.
    """
    length: Optional[confloat(ge=0.0)] = 10
    """
    Length of particle trails, in trail segments. If omitted, the renderer uses 12.
    """
    speed: Optional[float] = 0.2
    """
    Animation rate multiplier for particle movement (unitless, not a physical speed). 0 freezes the particles and a negative value advects them in reverse. If omitted, the renderer uses 1.
    """
    direction: Optional[str] = Field(
        'NAUTICAL_FROM', examples=['NAUTICAL_FROM', 'NAUTICAL_TO', 'CARTESIAN_RADIANS']
    )
    """
    Convention of the d datakey. 'NAUTICAL_FROM' (default): degrees clockwise from north, the direction the flow comes from. 'NAUTICAL_TO': degrees clockwise from north, the direction the flow goes to. 'CARTESIAN_RADIANS': mathematical angle in radians, counter-clockwise from east, the direction the flow goes to. Any other value is treated as a mathematical angle in degrees. Only used with the d and m datakeys.
    """


class Shape(Enum):
    """
    Shape of the particle mesh
    """

    cone = 'cone'
    arrow = 'arrow'
    quiver = 'quiver'


class Mesh(EidosModel):
    """
    Geometry of the glyph drawn for each particle. The object replaces the renderer defaults as a whole, so give shape, length and width together.
    """

    shape: Optional[Shape] = None
    """
    Shape of the particle mesh
    """
    length: Optional[confloat(ge=0.0)] = None
    """
    Length of the particle mesh (cone or arrow height, quiver extent along the flow), in relative units. The renderer default is 4.
    """
    width: Optional[confloat(ge=0.0)] = None
    """
    Width of the particle mesh (cone or arrow radius, quiver extent across the flow), in relative units. The renderer default is 1.
    """


class Partmesh(GriddedProps):
    """
    Animated mesh glyphs (cones, arrows or quivers) advected by the vector field.
    """

    speed: Optional[float] = 0.2
    """
    Animation rate multiplier for glyph movement (unitless, not a physical speed). 0 freezes the glyphs and a negative value advects them in reverse. If omitted, the renderer uses 1.
    """
    direction: Optional[str] = Field(
        'NAUTICAL_FROM', examples=['NAUTICAL_FROM', 'NAUTICAL_TO', 'CARTESIAN_RADIANS']
    )
    """
    Convention of the d datakey. 'NAUTICAL_FROM' (default): degrees clockwise from north, the direction the flow comes from. 'NAUTICAL_TO': degrees clockwise from north, the direction the flow goes to. 'CARTESIAN_RADIANS': mathematical angle in radians, counter-clockwise from east, the direction the flow goes to. Any other value is treated as a mathematical angle in degrees. Only used with the d and m datakeys.
    """
    mesh: Optional[Mesh] = None
    """
    Geometry of the glyph drawn for each particle. The object replaces the renderer defaults as a whole, so give shape, length and width together.
    """


class Contour(GriddedProps):
    """
    Contour lines of the scalar value, with optional labels. Supported for regular grids only.
    """

    levels: Optional[List[float]] = None
    """
    Contour level values, in display units (after scale and offset are applied). There is no automatic level selection: an empty or omitted list draws no contours.
    """
    lineWidth: Optional[conint(ge=0)] = 1
    """
    Line width for contour lines in pixels. 0 is treated as 1.
    """
    numLabels: Optional[confloat(ge=0.0)] = None
    """
    Number of contour labels per contour line. 0 draws no labels. Defaults to 1.
    """
    labelColor: Optional[common.Color] = None
    """
    Color for contour labels. The alpha component is ignored.
    """


class GridLayerDatakeys(EidosModel):
    """
    Mapping from data variables to scalar or vector values
    """

    c: Optional[str] = None
    """
    Scalar value variable mapped through the colormap: colors the pcolor cells and defines the contour lines. Optional when u and v are given, in which case the vector magnitude sqrt(u^2 + v^2) is used instead.
    """
    d: Optional[str] = None
    """
    Direction variable of a direction/magnitude vector pair, in degrees. By default interpreted as the nautical direction the flow is coming from; see the direction option of particles and partmesh. Used by particles and partmesh only, and must be paired with m.
    """
    m: Optional[str] = None
    """
    Magnitude variable of a direction/magnitude vector pair. Required whenever d is used.
    """
    u: Optional[str] = None
    """
    Eastward (x) vector component variable. Must be paired with v. Drives particles and partmesh, and colors pcolor by vector magnitude when c is not given.
    """
    v: Optional[str] = None
    """
    Northward (y) vector component variable. Must be paired with u.
    """
    z: Optional[str] = None
    """
    Elevation variable, overriding the datasource z coordkey. Geometry follows the variable's dimensions: same dimensions as x/y defines per-node elevation of the surface mesh (scaled by zscale, e.g. bathymetry); an own vertical dimension defines the level-selectable vertical axis of a data cube.
    """


class GriddedLayer(EidosModel):
    """
    World layer for visualizing gridded datasets such as sea surface temperature, wave height, wind speed, or any regularly-spaced data. Supports multiple visualization modes including pseudocolor plots, contour lines, particle animations, and vector fields. Ideal for environmental and oceanographic data visualization.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    """
    Follow the terrain surface. A layer with only pcolor content is draped onto the terrain; a layer with particles, partmesh or contour content is offset above it. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['gridded'] = 'gridded'
    """
    Layer type identifier. Must be 'gridded' for regularly-spaced data visualizations.
    """
    datakeys: GridLayerDatakeys
    """
    Mapping of data variables to coordinate and value fields. Defines how the data structure maps to spatial and temporal dimensions for visualization.
    """
    legend: Optional[common.Legend] = None
    """
    Configuration for the color scale legend display. Controls the appearance, position, and formatting of the legend that shows the data value to color mapping.
    """
    colormap: Optional[common.Colormap] = None
    """
    Color mapping configuration that translates data values to colors. Defines the color scale, value ranges, and visual encoding for the gridded data.
    """
    pcolor: Optional[Pcolor] = None
    """
    Pseudocolor rendering: colors each grid cell by the scalar value through the colormap.
    """
    particles: Optional[Particles] = None
    """
    Animated particle trails advected by the vector field given by the u/v or d/m datakeys.
    """
    partmesh: Optional[Partmesh] = None
    """
    Animated mesh glyphs (cones, arrows or quivers) advected by the vector field given by the u/v or d/m datakeys.
    """
    contour: Optional[Contour] = None
    """
    Contour lines of the scalar value at the given levels, with optional labels. Supported for regular grids only.
    """
    scale: Optional[float] = Field(1, examples=[1, 0.01, 100, 3.6])
    """
    Scaling factor applied to data values before visualization. Useful for unit conversion or value adjustment (e.g., scale: 0.01 to convert from centimeters to meters).
    """
    offset: Optional[float] = Field(0, examples=[0, -273.15, 32])
    """
    Offset value added to data values after scaling but before visualization. Useful for shifting data ranges or converting units (e.g., Kelvin to Celsius).
    """
    zscale: Optional[float] = None
    """
    Vertical exaggeration factor applied to a surface-geometry z datakey: displaces the pcolor mesh, particle and partmesh positions, and contour paths by altitude + zscale * z. Defaults to 1. Has no effect when the z datakey defines a vertical level axis.
    """
    units: Optional[str] = None
    """
    Units of the gridded value(s). Display only: shown on the legend color bar and not applied to the values.
    """
    landmask: Optional[bool] = None
    """
    Whether to apply a land mask to the gridded data to hide land areas.
    """
