# generated by datamodel-codegen:
#   filename:  node/worldlayer/label.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from typing import Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat, conint

from ... import data
from . import common


class LabelStyle(EidosModel):
    """
    Style properties for Label Layer labels
    """

    lineColor: Optional[common.Color] = None
    """
    Color of the lines. Reserved: not currently applied by the renderer, which draws the leader line in the label border color.
    """
    getBackgroundColor: Optional[common.StyleAccessor] = None
    """
    Background color of the label. The label background is drawn only when this property is set.
    """
    getFontColor: Optional[common.StyleAccessor] = None
    """
    Font color of the label. Defaults to black. When given as a constant color array it also tints the icon; otherwise the icon is white.
    """
    lineWidth: Optional[int] = 1
    """
    Width of the lines. Reserved: not currently applied by the renderer, which draws the leader line 1 pixel wide.
    """
    padding: Optional[conint(ge=0)] = 2
    """
    Padding around the label in pixels, applied equally on all sides
    """
    fontSize: Optional[conint(ge=0)] = 14
    """
    Font size of the label in pixels
    """
    fontFamily: Optional[str] = 'Monaco, monospace'
    """
    Font family of the label
    """
    fontWeight: Optional[str] = 'normal'
    """
    Font weight of the label
    """
    iconURL: Optional[str] = Field(
        '', examples=['icon://waves', 'icon://anchor?weight=bold']
    )
    """
    URL of icon to prepend to label. Either an absolute image URL (relative URLs are not supported: the label is then drawn without an icon) or a built-in Phosphor icon given as 'icon://<name>', with optional 'weight' (thin, light, regular, bold, fill or duotone; default regular) and 'color' query parameters. Leave empty for no icon.
    """
    iconScale: Optional[confloat(ge=0.0)] = 1.6
    """
    Icon size as a multiple of font size. 0 is treated as unset and falls back to 1.6.
    """


class LabelLayer(EidosModel):
    """
    World layer that places text labels on the map, one per data row, each joined to its location by a leader line. Label text is rendered from a Handlebars template, and labels are placed to avoid overlapping, up to a maximum number per view.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    """
    Interpret label z coordinates as height above the terrain surface. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['label'] = 'label'
    """
    Layer type identifier. Must be 'label' for text label layers.
    """
    labelTemplate: str
    """
    Label format string as Handlebars template, rendered once per data row with that row's variables as the context. See https://handlebarsjs.com/guide/#simple-expressions
    """
    geometry: Optional[data.Geometry] = None
    """
    Fallback GeoJSON geometry locating the labels. Used for any row for which the data source provides no geometry through its g coordkey.
    """
    colormap: Optional[common.Colormap] = None
    """
    Optional color mapping for data-driven label styling.
    """
    numberOfLabels: Optional[conint(ge=0)] = 20
    """
    Maximum number of labels placed in the view at once. 0 is treated as unset and falls back to 20.
    """
    lineLength: Optional[conint(ge=0)] = 1
    """
    Length of the leader line joining each label to its location, as a dimensionless multiplier that scales with the view so the line keeps a similar on-screen length. 0 is treated as unset and falls back to 1.
    """
    labelAngle: Optional[int] = 40
    """
    Starting angle in degrees of the search used to place each label around its location. 0 is treated as unset and falls back to 40.
    """
    style: Optional[LabelStyle] = None
    """
    Visual styling of the labels: text, background, leader line and optional icon.
    """
