# generated by datamodel-codegen:
#   filename:  node/worldlayer/scenegraph.json
#   timestamp: 2026-08-03T04:03:21+00:00

from __future__ import annotations

from typing import Literal, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field

from . import common


class Animate(EidosModel):
    """
    Play glTF animations, including skeletal (skinned) animation. true plays all clips, false disables animation, an object selects a clip and playback speed. When omitted, rigid-node animations play but skinned meshes stay in bind pose (legacy behaviour).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    clip: Optional[str] = None
    """
    Name of the animation clip to play (default: all clips)
    """
    speed: Optional[float] = 1
    """
    Playback speed multiplier
    """


class Gltf(EidosModel):
    """
    name or URLs of GLTF model keyed to data property
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_default: str = Field(..., alias='_default')
    """
    URL to default GLTF or GLB model
    """


class Scenegraph(EidosModel):
    key: Optional[str] = Field(None, title='Scenegraph key')
    """
    Data field to use as key for scenegraph model
    """
    gltf: Gltf = Field(..., title='GLTF models')
    """
    name or URLs of GLTF model keyed to data property
    """


class ScenegraphLayerDatakeys(EidosModel):
    """
    Mapping from data variables to geometry (orientation, offsets, scales). Point positions (x/y/z) and the time coordinate are resolved at runtime from the datasource coordkeys, not from these datakeys. EID-121: the per-axis scale keys are spelled xscale/yscale/zscale, matching what the layer reads; the legacy scalex/scaley/scalez spelling found in some older specs is accepted by additionalProperties and then silently ignored, so such a spec renders at unit scale.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    roll: Optional[str] = 'roll'
    pitch: Optional[str] = 'pitch'
    yaw: Optional[str] = 'yaw'
    xoffset: Optional[str] = 'xoffset'
    yoffset: Optional[str] = 'yoffset'
    zoffset: Optional[str] = 'zoffset'
    xscale: Optional[str] = 'xscale'
    yscale: Optional[str] = 'yscale'
    zscale: Optional[str] = 'zscale'


class Style(EidosModel):
    getColor: Optional[common.StyleAccessor] = None
    """
    Scenegraph model coloring
    """
    sizeScale: Optional[float] = 1
    """
    Scale factor for size
    """


class ScenegraphLayer(EidosModel):
    """
    Specification for Scenegraph layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    layerType: Literal['scenegraph'] = 'scenegraph'
    datakeys: ScenegraphLayerDatakeys
    colormap: Optional[common.Colormap] = None
    animate: Optional[Union[bool, Animate]] = Field(None, title='Animate')
    """
    Play glTF animations, including skeletal (skinned) animation. true plays all clips, false disables animation, an object selects a clip and playback speed. When omitted, rigid-node animations play but skinned meshes stay in bind pose (legacy behaviour).
    """
    scenegraph: Optional[Scenegraph] = None
    style: Optional[Style] = None
