# generated by datamodel-codegen:
#   filename:  node/worldlayer/scenegraph.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from typing import Literal, Optional, Union

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat

from . import common


class Animate(EidosModel):
    """
    Play glTF animations, including skeletal (skinned) animation. true plays all clips, false disables animation, an object selects a clip and playback speed. When omitted, rigid-node animations play but skinned meshes stay in bind pose (legacy behaviour).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    clip: Optional[str] = None
    """
    Name of the animation clip to play (default: all clips)
    """
    speed: Optional[float] = 1
    """
    Playback speed multiplier. 0 freezes the animation.
    """


class Gltf(EidosModel):
    """
    Map from values of the key data field to glTF or GLB model URLs. The _default entry is required and is used for any point without a matching entry.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field_default: str = Field(..., alias='_default')
    """
    URL to default GLTF or GLB model
    """


class Scenegraph(EidosModel):
    """
    The glTF models to draw, and the data field that selects between them.
    """

    key: Optional[str] = Field(None, title='Scenegraph key')
    """
    Data field whose value selects the model for each point from the gltf map. Points whose value has no entry in the map use _default. Must name a variable present in the data. When omitted, every point uses _default.
    """
    gltf: Gltf = Field(..., title='GLTF models')
    """
    Map from values of the key data field to glTF or GLB model URLs. The _default entry is required and is used for any point without a matching entry.
    """


class ScenegraphLayerDatakeys(EidosModel):
    """
    Mapping from data variables to geometry (orientation, offsets, scales). Point positions (x/y/z) and the time coordinate are resolved at runtime from the datasource coordkeys, not from these datakeys. EID-121: the per-axis scale keys are spelled xscale/yscale/zscale, matching what the layer reads; the legacy scalex/scaley/scalez spelling found in some older specs is accepted by additionalProperties and then silently ignored, so such a spec renders at unit scale.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    roll: Optional[str] = 'roll'
    """
    Roll variable, in degrees. The renderer adds 90 degrees to align the glTF model axes, so a data value of 0 leaves the model upright. Missing values are treated as 0.
    """
    pitch: Optional[str] = 'pitch'
    """
    Pitch variable, in degrees. Missing values are treated as 0.
    """
    yaw: Optional[str] = 'yaw'
    """
    Yaw variable (rotation about the vertical axis), in degrees. Missing values are treated as 0.
    """
    xoffset: Optional[str] = 'xoffset'
    """
    Variable giving the x offset of the model from its point location, in meters. Missing values are treated as 0.
    """
    yoffset: Optional[str] = 'yoffset'
    """
    Variable giving the y offset of the model from its point location, in meters. Missing values are treated as 0.
    """
    zoffset: Optional[str] = 'zoffset'
    """
    Variable giving the z offset of the model from its point location, in meters. Missing values are treated as 0.
    """
    xscale: Optional[str] = 'xscale'
    """
    Variable giving the scale factor of the model along its x axis. Missing or zero values are treated as 1.
    """
    yscale: Optional[str] = 'yscale'
    """
    Variable giving the scale factor of the model along its y axis. Missing or zero values are treated as 1.
    """
    zscale: Optional[str] = 'zscale'
    """
    Variable giving the scale factor of the model along its z axis. Missing or zero values are treated as 1.
    """


class Style(EidosModel):
    """
    Visual styling of the models.
    """

    getColor: Optional[common.StyleAccessor] = None
    """
    Scenegraph model coloring
    """
    sizeScale: Optional[confloat(ge=0.0)] = 1
    """
    Uniform scale factor applied to every model, on top of any per-point scale datakeys
    """


class ScenegraphLayer(EidosModel):
    """
    World layer that renders 3D glTF models at the point locations of a data source. Each point can be individually oriented, offset, scaled and colored from data variables, and models can play their glTF animations. Suited to vessels, platforms, vehicles, animals or any other positioned asset.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    """
    Interpret model z coordinates as height above the terrain surface. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['scenegraph'] = 'scenegraph'
    """
    Layer type identifier. Must be 'scenegraph' for 3D glTF model visualizations.
    """
    datakeys: ScenegraphLayerDatakeys
    """
    Mapping of data variables to the orientation, offset and scale of each model.
    """
    colormap: Optional[common.Colormap] = None
    """
    Optional color mapping for data-driven model coloring.
    """
    animate: Optional[Union[bool, Animate]] = Field(None, title='Animate')
    """
    Play glTF animations, including skeletal (skinned) animation. true plays all clips, false disables animation, an object selects a clip and playback speed. When omitted, rigid-node animations play but skinned meshes stay in bind pose (legacy behaviour).
    """
    scenegraph: Optional[Scenegraph] = None
    """
    The glTF models to draw, and the data field that selects between them.
    """
    style: Optional[Style] = None
    """
    Visual styling of the models.
    """
