# generated by datamodel-codegen:
#   filename:  node/worldlayer/seasurface.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from typing import List, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, constr

from ... import data as data_1
from . import common


class Offset(EidosModel):
    """
    Offsets for the model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    xoffset: Optional[float] = Field(0, title='X offset')
    """
    Eastward offset of the model instance from the floater position, in meters
    """
    yoffset: Optional[float] = Field(0, title='Y offset')
    """
    Northward offset of the model instance from the floater position, in meters
    """
    pitch: Optional[float] = Field(0, title='Pitch offset')
    """
    Static pitch of the model in degrees, added to the wave-induced pitch
    """
    zoffset: Optional[float] = Field(0, title='Heave offset')
    """
    Vertical offset of the model in meters, added to the wave-induced heave
    """
    roll: Optional[float] = Field(0, title='Roll offset')
    """
    Static roll of the model in degrees, added to the wave-induced roll
    """
    heading: Optional[float] = Field(0, title='Heading')
    """
    Heading of the model as a compass bearing in degrees, clockwise from north. Also the direction of travel when speed is set.
    """
    speed: Optional[float] = Field(0, title='Speed')
    """
    Speed of the floater in m/s along its heading. 0 is stationary and a negative value moves it astern. The speed also shifts the wave encounter frequency.
    """
    scale: Optional[float] = Field(1, title='Scale')
    """
    Uniform Scale factor. 0 is treated as unset and falls back to 1.
    """
    xscale: Optional[float] = Field(0, title='X scale')
    """
    Scale factor in x direction. 0 (the default) means unset: the uniform scale is used instead. A negative value mirrors the model along that axis.
    """
    yscale: Optional[float] = Field(0, title='Y scale')
    """
    Scale factor in y direction. 0 (the default) means unset: the uniform scale is used instead. A negative value mirrors the model along that axis.
    """
    zscale: Optional[float] = Field(0, title='Z scale')
    """
    Scale factor in z direction. 0 (the default) means unset: the uniform scale is used instead. A negative value mirrors the model along that axis.
    """


class SeaSurfaceLayerDatakeys(EidosModel):
    """
    Mapping from data variables to amplitude and phase
    """

    model_config = ConfigDict(
        extra='allow',
    )
    f: str = Field(..., title='Frequency')
    """
    Wave frequency variable, in Hz
    """
    d: str = Field(..., title='Direction')
    """
    Wave direction variable, in degrees clockwise from north, the direction the waves come from
    """
    efth: str = Field(..., title='Spectral variance')
    """
    Directional wave spectral density variable, in m^2/Hz/degree, with dimensions ordered [frequency, direction]
    """


class SeaSurfaceRaoDatakeys(EidosModel):
    """
    Mapping from data variables to amplitude and phase of motions
    """

    model_config = ConfigDict(
        extra='allow',
    )
    f: str = Field(..., title='Frequency')
    """
    RAO frequency variable, in Hz
    """
    d: str = Field(..., title='Direction')
    """
    RAO wave direction variable, in degrees clockwise from north, the direction the waves come from
    """
    pitch_amp: Optional[str] = Field('pitch_amp', title='Amplitude response')
    """
    Pitch amplitude response variable, per unit wave amplitude
    """
    pitch_pha: Optional[str] = Field('pitch_pha', title='Phase response')
    """
    Pitch phase response variable
    """
    roll_amp: Optional[str] = Field('roll_amp', title='Amplitude response')
    """
    Roll amplitude response variable, per unit wave amplitude
    """
    roll_pha: Optional[str] = Field('roll_pha', title='Phase response')
    """
    Roll phase response variable
    """
    heave_amp: str = Field(..., title='Amplitude response')
    """
    Heave amplitude response variable, per unit wave amplitude
    """
    heave_pha: str = Field(..., title='Phase response')
    """
    Heave phase response variable
    """


class Style(EidosModel):
    """
    Styling of the floater model.
    """

    getColor: Optional[common.StyleAccessor] = None
    """
    Floater model coloring
    """


class Rao(EidosModel):
    """
    Response Amplitude Operator describing the wave-induced heave, pitch and roll of the floater as a function of wave frequency and direction. When omitted, the floater follows the sea surface as a perfectly floating body (unit heave response, no pitch or roll). Not currently supported by the renderer: the RAO data source is not resolved, so omit this property.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    datakeys: SeaSurfaceRaoDatakeys
    """
    Mapping of data variables to the frequency, direction, amplitude and phase of the RAO.
    """
    data: str = Field(..., title='Data')
    """
    Name of the data source
    """


class Floater(EidosModel):
    """
    Floating object
    """

    id: str = Field(..., title='ID')
    """
    Unique identifier for the floater
    """
    name: Optional[str] = Field(None, title='Name')
    """
    Name of the floater
    """
    position: Optional[data_1.Point] = None
    """
    Location of the floater as a GeoJSON Point [longitude, latitude]. Defaults to the center of the current view.
    """
    gltf: constr(min_length=1) = Field(..., title='GLTF model')
    """
    URL of the glTF or GLB model
    """
    style: Optional[Style] = None
    """
    Styling of the floater model.
    """
    offsets: Optional[List[Offset]] = None
    """
    Array of position offsets, one for each model instance. One model instance is drawn per entry, so at least one entry (which may be an empty object) is needed for the floater to be drawn.
    """
    rao: Optional[Rao] = Field(None, title='RAO')
    """
    Response Amplitude Operator describing the wave-induced heave, pitch and roll of the floater as a function of wave frequency and direction. When omitted, the floater follows the sea surface as a perfectly floating body (unit heave response, no pitch or roll). Not currently supported by the renderer: the RAO data source is not resolved, so omit this property.
    """


class SeaSurfaceLayer(EidosModel):
    """
    World layer that renders an animated 3D sea surface synthesized from a directional wave spectrum, with optional floating glTF models (floaters) that move with the waves.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layerType: Literal['seasurface'] = 'seasurface'
    """
    Layer type identifier. Must be 'seasurface' for animated sea surface visualizations.
    """
    datakeys: SeaSurfaceLayerDatakeys
    """
    Mapping of data variables to the frequency, direction and spectral density of the directional wave spectrum.
    """
    zscale: Optional[float] = Field(1, title='Vertical scale')
    """
    Vertical exaggeration of the sea surface elevation. Also scales the wave-induced heave, pitch and roll of floaters.
    """
    elevation: Optional[float] = Field(0, title='Sea level elevation')
    """
    Elevation of mean sea level in metres
    """
    floaters: Optional[List[Floater]] = Field([], title='Floaters')
    """
    List of floating objects
    """
