# generated by datamodel-codegen:
#   filename:  node/worldlayer/track.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat, constr

from . import common


class Track(EidosModel):
    """
    Track configuration: how positions are grouped into tracks, how much history is drawn, and which properties are shown.
    """

    key: Optional[str] = Field(None, title='Track key')
    """
    Data field to use as key for grouping tracks. When omitted, all positions form a single track.
    """
    history: Optional[constr(pattern=r'^-?P')] = Field(
        'PT1H', examples=['PT1H', 'PT6H', 'P30D'], title='Track history'
    )
    """
    Length of previous positions to show before the current time, as an ISO 8601 duration (e.g. 'PT6H', 'P30D')
    """
    properties: Optional[List[str]] = Field([], title='Track properties')
    """
    Data variables copied onto each track segment, for use in tooltips and style accessors. Every name must be a variable present in the data.
    """


class WidthUnits(str, Enum):
    """
    The units of the track width. Default: 'pixels'.
    """

    meters = 'meters'
    pixels = 'pixels'


class TrackLayerStyle(EidosModel):
    """
    Style properties for Track Layer features
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    getColor: Optional[common.StyleAccessor] = None
    """
    The solid color of the track in the format [r, g, b, [a]]. Default: [0, 0, 0, 255].
    """
    getWidth: Optional[common.StyleAccessor] = None
    """
    The width of the track in width units. Default: 1.
    """
    widthUnits: Optional[WidthUnits] = 'pixels'
    """
    The units of the track width. Default: 'pixels'.
    """
    opacity: Optional[confloat(ge=0.0, le=1.0)] = None
    """
    The opacity of the track, from 0 (fully transparent) to 1 (fully opaque). Default: 1.
    """


class TrackLayer(EidosModel):
    """
    Specification for Track overlay layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    """
    Interpret track z coordinates as height above the terrain surface. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['track'] = 'track'
    """
    Layer type identifier. Must be 'track' for moving-object track visualizations.
    """
    colormap: Optional[common.Colormap] = None
    """
    Optional color mapping for data-driven track styling.
    """
    style: Optional[TrackLayerStyle] = None
    """
    Visual styling of the tracks: color, width, width units and opacity.
    """
    track: Track
    """
    Track configuration: how positions are grouped into tracks, how much history is drawn, and which properties are shown.
    """
    legend: Optional[common.Legend] = None
    """
    Configuration for the legend shown for this layer in the layer selector.
    """
