# generated by datamodel-codegen:
#   filename:  node/worldlayer/wmts.json
#   timestamp: 2026-09-20T02:05:10+00:00

from __future__ import annotations

from typing import Literal, Optional

from eidosxr.spec._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat, constr

from . import common


class WmtsDatakeys(EidosModel):
    """
    Mapping from WMTS dimension identifiers to time and depth.
    """

    t: Optional[str] = Field(None, examples=['time', 'TIME'])
    """
    Identifier of the time dimension of the WMTS layer, as listed in the service capabilities. The dimension value closest to the world node's current time is requested. Only takes effect when layerName is set.
    """
    z: Optional[str] = Field(None, examples=['elevation', 'ELEVATION'])
    """
    Identifier of the depth or elevation dimension of the WMTS layer. Reserved: not currently used by the renderer.
    """


class WmtsLayerSpec(EidosModel):
    """
    Specification for WMTS layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    """
    Drape the tiles over the terrain surface. Requires the world node terrain option to be enabled.
    """
    layerType: Literal['wmts'] = 'wmts'
    """
    Layer type identifier. Must be 'wmts' for OGC Web Map Tile Service raster layers.
    """
    capabilitiesUrl: constr(min_length=1)
    """
    Base URL for the WMTS service GetCapabilities endpoint. Must not include a query string: '?service=WMTS&request=GetCapabilities' is appended when the capabilities are fetched.
    """
    refreshCapabilities: Optional[str] = Field(None, examples=['PT1H', 'P1D'])
    """
    Refresh interval for capabilities in ISO8601 duration format (e.g., 'P1D'). When omitted, or when the value is not a valid duration, cached capabilities are never refreshed.
    """
    datakeys: Optional[WmtsDatakeys] = None
    """
    Mapping from WMTS dimension identifiers to the world node's time and level selection.
    """
    layerName: Optional[str] = None
    """
    Name of the layer to display from the WMTS service. If not specified, uses the first available layer
    """
    layerStyle: Optional[str] = None
    """
    Style identifier (e.g., 'default', 'color', 'gray'). If not specified, uses the first available style
    """
    tileMatrixSet: Optional[str] = None
    """
    TileMatrixSet identifier (e.g., 'EPSG:4326', 'EPSG:3857'). If not specified, uses the first available TileMatrixSet
    """
    legend: Optional[common.Legend] = None
    """
    Configuration for the color scale legend display. Controls the appearance, position, and formatting of the legend that shows the data value to color mapping.
    """
    opacity: Optional[confloat(ge=0.0, le=1.0)] = 1
    """
    Layer opacity (0-1)
    """
