# generated by datamodel-codegen:
#   filename:  node/worldlayer/feature.json
#   timestamp: 2026-08-01T06:42:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AnyUrl, ConfigDict, Field, RootModel

from eidosxr._basemodel import EidosModel


class ScaledColormap(EidosModel):
    """
    Predefined colormap
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    scale: List[str]
    """
    Scale of the colormap
    """
    domain: List[Union[float, str]]
    """
    Domain of the colormap (min and max values or values )
    """


class Name(str, Enum):
    """
    Name of the preset colormap
    """

    turbo = 'turbo'
    viridis = 'viridis'
    cividis = 'cividis'
    inferno = 'inferno'
    magma = 'magma'
    plasma = 'plasma'
    d3 = 'd3'
    g10 = 'g10'
    t10 = 't10'
    alphabet = 'alphabet'
    dark24 = 'dark24'
    light24 = 'light24'
    twilight = 'twilight'
    icefire = 'icefire'
    edge = 'edge'
    phase = 'phase'
    hsv = 'hsv'
    mrybm = 'mrybm'
    mygbm = 'mygbm'
    turbid = 'turbid'
    thermal = 'thermal'
    haline = 'haline'
    solar = 'solar'
    ice = 'ice'
    gray = 'gray'
    oxy = 'oxy'
    deep = 'deep'
    dense = 'dense'
    algae = 'algae'
    matter = 'matter'
    speed = 'speed'
    amp = 'amp'
    tempo = 'tempo'
    balance = 'balance'
    delta = 'delta'
    curl = 'curl'
    wind = 'wind'
    wave = 'wave'
    purples = 'purples'
    blues = 'blues'
    greens = 'greens'
    oranges = 'oranges'
    reds = 'reds'
    ylorbr = 'ylorbr'
    ylorrd = 'ylorrd'
    orrd = 'orrd'
    purd = 'purd'
    rdpu = 'rdpu'
    bupu = 'bupu'
    pubu = 'pubu'
    pubugn = 'pubugn'
    gnbu = 'gnbu'
    bugn = 'bugn'
    ylgnbu = 'ylgnbu'
    ylgn = 'ylgn'
    greys = 'greys'
    spectral = 'spectral'
    rdylgn = 'rdylgn'
    rdbu = 'rdbu'
    piyg = 'piyg'
    prgn = 'prgn'
    rdylbu = 'rdylbu'
    brbg = 'brbg'
    rdgy = 'rdgy'
    set1 = 'set1'
    pastel1 = 'pastel1'
    dark2 = 'dark2'
    set2 = 'set2'
    pastel2 = 'pastel2'
    set3 = 'set3'


class PresetColormap(EidosModel):
    """
    Predefined colormap
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name
    """
    Name of the preset colormap
    """
    domain: Optional[List[float]] = Field(None, max_length=20, min_length=2)
    """
    Domain of the preset colormap (min and max values)
    """


class Color(RootModel[Union[List[float], str]]):
    root: Union[List[float], str] = Field(..., title='Color')
    """
    Color definition
    """


class StyleAccessorString(RootModel[str]):
    root: str = Field(..., title='Style accessor constant string')
    """
    Constant value
    """


class StyleAccessorNumber(RootModel[float]):
    root: float = Field(..., title='Style accessor constant number')
    """
    Constant value
    """


class StyleAccessorArray(RootModel[List[float]]):
    """
    Array of constant values
    """

    root: List[float] = Field(..., title='Style accessor constant array')
    """
    Array of constant values
    """


class StyleAccessorTemplate(EidosModel):
    """
    Template accessor
    """

    template: str
    """
    Template string
    """


class StyleAccessorFunction(EidosModel):
    """
    Accessor function
    """

    function: str
    """
    Accessor function identifier
    """
    args: List[str]
    """
    Arguments for accessor function
    """


class LegendSpec(EidosModel):
    """
    Legend properties
    """

    title: Optional[str] = None
    """
    Legend title
    """
    labels: Optional[List[Union[str, float]]] = None
    """
    Legend labels
    """
    url: Optional[AnyUrl] = None
    """
    URL to an external legend image
    """


class Legend(RootModel[Optional[Union[LegendSpec, bool]]]):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: Optional[Union[LegendSpec, bool]] = Field(..., title='Legend definition')
    """
    Legend properties
    """


class Colormap(RootModel[Union[PresetColormap, ScaledColormap]]):
    root: Union[PresetColormap, ScaledColormap] = Field(..., title='Colormap')
    """
    Scale and domain argument for chroma.scale colormap definition
    """


class StyleAccessor(
    RootModel[
        Union[
            StyleAccessorString,
            StyleAccessorNumber,
            StyleAccessorFunction,
            StyleAccessorArray,
            StyleAccessorTemplate,
        ]
    ]
):
    root: Union[
        StyleAccessorString,
        StyleAccessorNumber,
        StyleAccessorFunction,
        StyleAccessorArray,
        StyleAccessorTemplate,
    ] = Field(..., title='Style accessor definition')
    """
    Style properties
    """


class FeatureStyle(EidosModel):
    """
    Style properties for Feature Layer features
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    opacity: Optional[float] = None
    """
    Opacity of the layer. Default: 1.
    """
    pointType: Optional[str] = None
    """
    How to render Point and MultiPoint features in the data. Supported types are 'circle', 'icon', 'text'. To use more than one type, join the names with '+', for example 'icon+text'. Default: 'circle'.
    """
    filled: Optional[bool] = None
    """
    Whether to draw filled polygons (solid fill) and points (circles). Default: true.
    """
    getFillColor: Optional[StyleAccessor] = None
    """
    The solid color of the polygon and points (circles) in the format [r, g, b, [a]]. Default: [0, 0, 0, 255].
    """
    stroked: Optional[bool] = None
    """
    Whether to draw an outline around polygons and points (circles). Default: true.
    """
    getLineColor: Optional[StyleAccessor] = None
    """
    The rgba color of a line in the format [r, g, b, [a]]. Default: [0, 0, 0, 255].
    """
    getLineWidth: Optional[StyleAccessor] = None
    """
    The width of a line in units specified by lineWidthUnits. Default: 1.
    """
    lineWidthUnits: Optional[str] = None
    """
    The units of the line width, one of 'meters', 'common', and 'pixels'. Default: 'meters'.
    """
    lineWidthScale: Optional[float] = None
    """
    A multiplier that is applied to all line widths. Default: 1.
    """
    lineWidthMinPixels: Optional[float] = None
    """
    The minimum line width in pixels. Default: 0.
    """
    lineWidthMaxPixels: Optional[float] = None
    """
    The maximum line width in pixels. Default: 9007199254740991.
    """
    lineCapRounded: Optional[bool] = None
    """
    Type of line caps. If true, draw round caps. Otherwise draw square caps. Default: false.
    """
    lineJointRounded: Optional[bool] = None
    """
    Type of line joint. If true, draw round joints. Otherwise draw miter joints. Default: false.
    """
    lineMiterLimit: Optional[float] = None
    """
    The maximum extent of a joint in ratio to the stroke width. Default: 4.
    """
    lineBillboard: Optional[bool] = None
    """
    If true, extrude the line in screen space (width always faces the camera). Default: false.
    """
    extruded: Optional[bool] = None
    """
    Extrude Polygon and MultiPolygon features along the z-axis if set to true. Default: false.
    """
    wireframe: Optional[bool] = None
    """
    Whether to generate a line wireframe of the hexagon. Default: false.
    """
    getElevation: Optional[StyleAccessor] = None
    """
    The elevation of a polygon feature (when extruded is true). Default: 1000.
    """
    elevationScale: Optional[float] = None
    """
    Elevation multiplier. The final elevation is calculated by elevationScale * getElevation(d). Default: 1.
    """
    material: Optional[Dict[str, Any]] = None
    """
    An object that contains material props for lighting effect applied on extruded polygons. Default: {}.
    """
    field_full3d: Optional[bool] = Field(None, alias='_full3d')
    """
    Experimental property. When true, polygon tessellation will be performed on the plane with the largest area, instead of the xy plane. Default: false.
    """
    getPointRadius: Optional[StyleAccessor] = None
    """
    Radius of points when pointType is 'circle'. Default: 1.
    """
    pointRadiusUnits: Optional[str] = None
    """
    Units for point radius when pointType is 'circle'. Default: 'meters'.
    """
    pointRadiusScale: Optional[float] = None
    """
    Scale for point radius when pointType is 'circle'. Default: 1.
    """
    pointRadiusMinPixels: Optional[float] = None
    """
    Minimum point radius in pixels when pointType is 'circle'. Default: 0.
    """
    pointRadiusMaxPixels: Optional[float] = None
    """
    Maximum point radius in pixels when pointType is 'circle'. Default: 9007199254740991.
    """
    pointAntialiasing: Optional[bool] = None
    """
    Whether to use antialiasing for points when pointType is 'circle'. Default: true.
    """
    pointBillboard: Optional[bool] = None
    """
    If true, point is billboarded when pointType is 'circle'. Default: false.
    """
    iconAtlas: Optional[str] = None
    """
    URL of the icon atlas image when pointType is 'icon'. Default: null.
    """
    iconMapping: Optional[Dict[str, Any]] = None
    """
    Mapping of icon names to positions in the atlas when pointType is 'icon'. Default: {}.
    """
    getIcon: Optional[StyleAccessor] = None
    """
    Accessor for icon names when pointType is 'icon'. Default: f => f.properties.icon.
    """
    getIconSize: Optional[StyleAccessor] = None
    """
    Size of icons when pointType is 'icon'. Default: 1.
    """
    getIconColor: Optional[StyleAccessor] = None
    """
    Color of icons when pointType is 'icon'. Default: [0, 0, 0, 255].
    """
    getIconAngle: Optional[StyleAccessor] = None
    """
    Rotation angle of icons when pointType is 'icon'. Default: 0.
    """
    getIconPixelOffset: Optional[StyleAccessor] = None
    """
    Pixel offset of icons when pointType is 'icon'. Default: [0, 0].
    """
    iconSizeUnits: Optional[str] = None
    """
    Units for icon size when pointType is 'icon'. Default: 'pixels'.
    """
    iconSizeScale: Optional[float] = None
    """
    Scale for icon size when pointType is 'icon'. Default: 1.
    """
    iconSizeMinPixels: Optional[float] = None
    """
    Minimum icon size in pixels when pointType is 'icon'. Default: 0.
    """
    iconSizeMaxPixels: Optional[float] = None
    """
    Maximum icon size in pixels when pointType is 'icon'. Default: 9007199254740991.
    """
    iconBillboard: Optional[bool] = None
    """
    If true, icons are billboarded when pointType is 'icon'. Default: true.
    """
    iconAlphaCutoff: Optional[float] = None
    """
    Alpha cutoff for icons when pointType is 'icon'. Default: 0.05.
    """
    getText: Optional[StyleAccessor] = None
    """
    Accessor for text content when pointType is 'text'. Default: f => f.properties.text.
    """
    getTextColor: Optional[StyleAccessor] = None
    """
    Color of text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    getTextAngle: Optional[StyleAccessor] = None
    """
    Rotation angle of text when pointType is 'text'. Default: 0.
    """
    getTextSize: Optional[StyleAccessor] = None
    """
    Size of text when pointType is 'text'. Default: 32.
    """
    getTextAnchor: Optional[StyleAccessor] = None
    """
    Anchor position of text when pointType is 'text'. Default: 'middle'.
    """
    getTextAlignmentBaseline: Optional[StyleAccessor] = None
    """
    Alignment baseline of text when pointType is 'text'. Default: 'center'.
    """
    getTextPixelOffset: Optional[StyleAccessor] = None
    """
    Pixel offset of text when pointType is 'text'. Default: [0, 0].
    """
    getTextBackgroundColor: Optional[StyleAccessor] = None
    """
    Background color of text when pointType is 'text'. Default: [255, 255, 255, 255].
    """
    getTextBorderColor: Optional[StyleAccessor] = None
    """
    Border color of text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    getTextBorderWidth: Optional[StyleAccessor] = None
    """
    Border width of text when pointType is 'text'. Default: 0.
    """
    textSizeUnits: Optional[str] = None
    """
    Units for text size when pointType is 'text'. Default: 'pixels'.
    """
    textSizeScale: Optional[float] = None
    """
    Scale for text size when pointType is 'text'. Default: 1.
    """
    textSizeMinPixels: Optional[float] = None
    """
    Minimum text size in pixels when pointType is 'text'. Default: 0.
    """
    textSizeMaxPixels: Optional[float] = None
    """
    Maximum text size in pixels when pointType is 'text'. Default: 9007199254740991.
    """
    textCharacterSet: Optional[str] = None
    """
    Character set for text when pointType is 'text'. Default: 'ASCII chars 32-128'.
    """
    textFontFamily: Optional[str] = None
    """
    Font family for text when pointType is 'text'. Default: 'Monaco, monospace'.
    """
    textFontWeight: Optional[str] = None
    """
    Font weight for text when pointType is 'text'. Default: 'normal'.
    """
    textLineHeight: Optional[float] = None
    """
    Line height for text when pointType is 'text'. Default: 1.
    """
    textMaxWidth: Optional[float] = None
    """
    Maximum width for text when pointType is 'text'. Default: -1.
    """
    textWordBreak: Optional[str] = None
    """
    Word break setting for text when pointType is 'text'. Default: 'break-word'.
    """
    textBackground: Optional[bool] = None
    """
    Whether text has a background when pointType is 'text'. Default: false.
    """
    textBackgroundPadding: Optional[List[float]] = None
    """
    Padding for text background when pointType is 'text'. Default: [0, 0].
    """
    textOutlineColor: Optional[StyleAccessor] = None
    """
    Outline color for text when pointType is 'text'. Default: [0, 0, 0, 255].
    """
    textOutlineWidth: Optional[float] = None
    """
    Outline width for text when pointType is 'text'. Default: 0.
    """
    textBillboard: Optional[bool] = None
    """
    If true, text is billboarded when pointType is 'text'. Default: true.
    """
    textFontSettings: Optional[Dict[str, Any]] = None
    """
    Additional font settings for text when pointType is 'text'. Default: {}.
    """


class FeatureLayer(EidosModel):
    """
    World layer for displaying vector geographic features such as points, lines, and polygons. Ideal for showing discrete objects like weather stations, ship positions, port locations, administrative boundaries, or custom geographic shapes. Features can be styled with colors, symbols, and labels.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layerType: Literal['feature']
    """
    Layer type identifier. Must be 'feature' for vector geographic data visualizations.
    """
    colormap: Optional[Colormap] = None
    """
    Optional color mapping for data-driven feature styling. When provided, feature colors are determined by data values rather than fixed style properties.
    """
    legend: Optional[Legend] = None
    style: FeatureStyle
    """
    Visual styling properties for features including colors, sizes, stroke properties, and opacity. These styles are applied to all features unless overridden by colormap-based styling.
    """
