# generated by datamodel-codegen:
#   filename:  node/worldlayer/gridded.json
#   timestamp: 2026-08-03T02:03:45+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from pydantic import ConfigDict, Field, RootModel

from eidosxr._basemodel import EidosModel

from . import common


class GriddedProps(EidosModel):
    altitude: Optional[float] = None
    """
    Uniform altitude offset for all gridded elements in meters
    """
    opacity: Optional[float] = 1.0
    """
    Opacity of the gridded elements
    """
    color: Optional[common.Color] = None
    """
    Uniform color for all gridded elements
    """


class Pcolor(RootModel[GriddedProps]):
    root: GriddedProps


class Particles(GriddedProps):
    size: Optional[float] = None
    length: Optional[float] = 10
    """
    Length of particle trails
    """
    speed: Optional[float] = 0.2
    """
    Speed of particle movement
    """


class Shape(Enum):
    """
    Shape of the particle mesh
    """

    cone = 'cone'
    arrow = 'arrow'
    quiver = 'quiver'


class Mesh(EidosModel):
    shape: Optional[Shape] = None
    """
    Shape of the particle mesh
    """
    length: Optional[float] = None
    """
    Length of the particle mesh
    """
    width: Optional[float] = None
    """
    Width of the particle mesh
    """


class Partmesh(GriddedProps):
    speed: Optional[float] = 0.2
    """
    Speed of particle movement
    """
    mesh: Optional[Mesh] = None


class Contour(GriddedProps):
    levels: Optional[List[float]] = None
    """
    Contour levels values
    """
    lineWidth: Optional[int] = 1
    """
    Line width for contour lines
    """
    numLabels: Optional[float] = None
    """
    Number of contour labels per contour line
    """
    labelColor: Optional[common.Color] = None
    """
    Color for contour labels
    """


class GridLayerDatakeys(EidosModel):
    """
    Mapping from data variables to scalar or vector values
    """

    c: Optional[str] = None
    d: Optional[str] = None
    m: Optional[str] = None
    u: Optional[str] = None
    v: Optional[str] = None
    z: Optional[str] = None
    """
    Elevation variable, overriding the datasource z coordkey. Geometry follows the variable's dimensions: same dimensions as x/y defines per-node elevation of the surface mesh (scaled by zscale, e.g. bathymetry); an own vertical dimension defines the level-selectable vertical axis of a data cube.
    """


class GriddedLayer(EidosModel):
    """
    World layer for visualizing gridded datasets such as sea surface temperature, wave height, wind speed, or any regularly-spaced data. Supports multiple visualization modes including pseudocolor plots, contour lines, particle animations, and vector fields. Ideal for environmental and oceanographic data visualization.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    terrainFollow: Optional[common.TerrainFollow] = False
    layerType: Literal['gridded']
    """
    Layer type identifier. Must be 'gridded' for regularly-spaced data visualizations.
    """
    datakeys: GridLayerDatakeys
    """
    Mapping of data variables to coordinate and value fields. Defines how the data structure maps to spatial and temporal dimensions for visualization.
    """
    legend: Optional[common.Legend] = None
    """
    Configuration for the color scale legend display. Controls the appearance, position, and formatting of the legend that shows the data value to color mapping.
    """
    colormap: Optional[common.Colormap] = None
    """
    Color mapping configuration that translates data values to colors. Defines the color scale, value ranges, and visual encoding for the gridded data.
    """
    pcolor: Optional[Pcolor] = None
    particles: Optional[Particles] = None
    partmesh: Optional[Partmesh] = None
    contour: Optional[Contour] = None
    scale: Optional[float] = Field(1, examples=[1, 0.01, 100, 3.6])
    """
    Scaling factor applied to data values before visualization. Useful for unit conversion or value adjustment (e.g., scale: 0.01 to convert from centimeters to meters).
    """
    offset: Optional[float] = Field(0, examples=[0, -273.15, 32])
    """
    Offset value added to data values after scaling but before visualization. Useful for shifting data ranges or converting units (e.g., Kelvin to Celsius).
    """
    zscale: Optional[float] = None
    """
    Vertical exaggeration factor applied to a surface-geometry z datakey: displaces the pcolor mesh, particle and partmesh positions, and contour paths by altitude + zscale * z.
    """
    units: Optional[str] = None
    """
    Units of the gridded value(s)
    """
    landmask: Optional[bool] = None
    """
    Whether to apply a land mask to the gridded data to hide land areas.
    """
