# generated by datamodel-codegen:
#   filename:  node/worldlayer/label.json
#   timestamp: 2026-08-01T06:42:43+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import ConfigDict, Field, RootModel

from eidosxr._basemodel import EidosModel

from . import feature


class Point(EidosModel):
    """
    Point Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[Union[float, int]] = Field(..., title='Coordinates')
    type: Literal['Point'] = Field('Point', title='Type')


class MultiPoint(EidosModel):
    """
    MultiPoint Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[List[Union[float, int]]] = Field(
        ..., min_length=1, title='Coordinates'
    )
    type: Literal['MultiPoint'] = Field('MultiPoint', title='Type')


class LineString(EidosModel):
    """
    LineString Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[List[Union[float, int]]] = Field(
        ..., min_length=2, title='Coordinates'
    )
    type: Literal['LineString'] = Field('LineString', title='Type')


class Coordinate(RootModel[List[List[Union[float, int]]]]):
    root: List[List[Union[float, int]]]


class MultiLineString(EidosModel):
    """
    MultiLineString Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[Coordinate] = Field(..., min_length=1, title='Coordinates')
    type: Literal['MultiLineString'] = Field('MultiLineString', title='Type')


class Polygon(EidosModel):
    """
    Polygon Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[Coordinate] = Field(..., min_length=1, title='Coordinates')
    type: Literal['Polygon'] = Field('Polygon', title='Type')


class Coordinate5Item(RootModel[List[List[Union[float, int]]]]):
    root: List[List[Union[float, int]]]


class Coordinate5(RootModel[List[Coordinate5Item]]):
    root: List[Coordinate5Item]


class MultiPolygon(EidosModel):
    """
    MultiPolygon Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    coordinates: List[Coordinate5] = Field(..., min_length=1, title='Coordinates')
    type: Literal['MultiPolygon'] = Field('MultiPolygon', title='Type')


class Type(str, Enum):
    Feature = 'Feature'


class LabelStyle(EidosModel):
    lineColor: Optional[feature.Color] = None
    """
    Color of the lines
    """
    getBackgroundColor: Optional[feature.StyleAccessor] = None
    """
    Background color of the label
    """
    getFontColor: Optional[feature.StyleAccessor] = None
    """
    Font color of the label
    """
    lineWidth: Optional[int] = 1
    """
    Width of the lines
    """
    padding: Optional[int] = 2
    """
    Padding around the label
    """
    fontSize: Optional[int] = 14
    """
    Font size of the label
    """
    fontFamily: Optional[str] = 'Monaco, monospace'
    """
    Font family of the label
    """
    fontWeight: Optional[str] = 'normal'
    """
    Font weight of the label
    """
    iconURL: Optional[str] = ''
    """
    URL of icon to prepend to label
    """
    iconScale: Optional[float] = 1.6
    """
    Icon size as a multiple of font size
    """


class LabelLayer(EidosModel):
    """
    Specification for Label overlay layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layerType: Literal['label']
    labelTemplate: str
    """
    Label format string as Handlebars template. See https://handlebarsjs.com/guide/#simple-expressions
    """
    geometry: Optional[Geometry] = None
    colormap: Optional[feature.Colormap] = None
    numberOfLabels: Optional[int] = 20
    """
    Number of labels to show
    """
    lineLength: Optional[int] = 1
    """
    Length of the anchor line
    """
    labelAngle: Optional[int] = 40
    """
    Angle of the label anchor
    """
    style: Optional[LabelStyle] = None


class Geometry(
    RootModel[
        Union[
            Point,
            MultiPoint,
            LineString,
            MultiLineString,
            Polygon,
            MultiPolygon,
            GeometryCollection,
        ]
    ]
):
    root: Union[
        Point,
        MultiPoint,
        LineString,
        MultiLineString,
        Polygon,
        MultiPolygon,
        GeometryCollection,
    ] = Field(..., title='Geometry')
    """
    Geometry Model
    """


class GeometryCollection(EidosModel):
    """
    GeometryCollection Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['GeometryCollection'] = Field('GeometryCollection', title='Type')
    geometries: List[Geometry] = Field(..., title='Geometries')


class Feature(EidosModel):
    """
    Feature Model
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type = Field(..., title='Type')
    geometry: Geometry
    properties: Optional[Dict[str, Any]] = Field(None, title='Properties')
    id: Optional[str] = Field(None, title='Id')
    bbox: Optional[List[Union[float, int]]] = Field(None, title='Bbox')


class FeatureCollection(EidosModel):
    type: Literal['FeatureCollection']
    features: List[Feature]


LabelLayer.model_rebuild()
Geometry.model_rebuild()
